// <auto-generated>
//     This code was generated by GenerateRequestCmdlets.ps1 (version 1.0.0) on 2025-10-30T06:56:17.9874161+00:00.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member

using System;
using System.Text;
using System.Management.Automation;
using Microsoft.Xrm.Sdk;
using Microsoft.Xrm.Sdk.Messages;
using Microsoft.Crm.Sdk.Messages;
using Microsoft.PowerPlatform.Dataverse.Client;
using Rnwood.Dataverse.Data.PowerShell.Commands;

namespace Rnwood.Dataverse.Data.PowerShell.Commands.Sdk
{
    /// <summary>
    /// Contains the data that is needed to add a solution component to an unmanaged solution.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("GenerateRequestCmdlets.ps1", "1.0.0")]
    [System.Diagnostics.DebuggerNonUserCode]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [Cmdlet("Invoke", "DataverseAddSolutionComponent", SupportsShouldProcess = true, ConfirmImpact = ConfirmImpact.Medium)]
    public class InvokeDataverseAddSolutionComponentCmdlet : OrganizationServiceCmdlet
    {

        

        

                /// <summary>
        /// Gets or sets the ID of the solution component. Required.
        /// </summary>

        [Parameter(HelpMessage = "Gets or sets the ID of the solution component. Required.")]
        public System.Guid ComponentId { get; set; }

        /// <summary>
        /// Gets or sets the value that represents the solution component that you are adding. Required.
        /// </summary>

        [Parameter(HelpMessage = "Gets or sets the value that represents the solution component that you are adding. Required.")]
        public System.Int32 ComponentType { get; set; }

        /// <summary>
        /// Gets or sets the name of the unmanaged solution to which you want to add this column. Optional.
        /// </summary>

        [Parameter(HelpMessage = "Gets or sets the name of the unmanaged solution to which you want to add this column. Optional.")]
        public System.String SolutionUniqueName { get; set; }

        /// <summary>
        /// Gets or sets a value that indicates whether other solution components that are required by the solution component that you are adding should also be added to the unmanaged solution. Required.
        /// </summary>

        [Parameter(HelpMessage = "Gets or sets a value that indicates whether other solution components that are required by the solution component that you are adding should also be added to the unmanaged solution. Required.")]
        public System.Boolean AddRequiredComponents { get; set; }

        /// <summary>
        /// Indicates whether the subcomponents should be included.
        /// </summary>

        [Parameter(HelpMessage = "Indicates whether the subcomponents should be included.")]
        public System.Boolean DoNotIncludeSubcomponents { get; set; }

        /// <summary>
        /// Gets or sets a value that specifies if the component is added to the solution with its metadata.
        /// </summary>

        [Parameter(HelpMessage = "Gets or sets a value that specifies if the component is added to the solution with its metadata.")]
        public System.String[] IncludedComponentSettingsValues { get; set; }

                /// <summary>
        /// Processes the cmdlet request and writes the response to the pipeline.
        /// </summary>
        protected override void ProcessRecord()
        {
            base.ProcessRecord();

            var request = new Microsoft.Crm.Sdk.Messages.AddSolutionComponentRequest();
                        request.ComponentId = ComponentId;
            request.ComponentType = ComponentType;
            request.SolutionUniqueName = SolutionUniqueName;
            request.AddRequiredComponents = AddRequiredComponents;
            request.DoNotIncludeSubcomponents = DoNotIncludeSubcomponents;
            request.IncludedComponentSettingsValues = IncludedComponentSettingsValues;

            // Build a short serialized summary of the request for ShouldProcess output
            var requestSummary = new StringBuilder();
            try
            {
                var props = request.GetType().GetProperties(System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.Instance);
                foreach (var p in props)
                {
                    object val = null;
                    try { val = p.GetValue(request); } catch { val = null; }
                    var vstr = val == null ? "null" : val.ToString();
                    requestSummary.Append(p.Name).Append("=").Append(vstr).Append("; ");
                }
            }
            catch
            {
                // Ignore any errors while serializing the request for what-if messaging
            }

            // Emit verbose output of the serialized request when -Verbose is used
            try { WriteVerbose(requestSummary.ToString()); } catch { }

            // Support -WhatIf and -Confirm; include request summary in the action description
            if (!ShouldProcess(request.GetType().Name, requestSummary.ToString()))
            {
                return;
            }

            var response = Connection.Execute(request);
            WriteObject(response);
        }
    }
}

#pragma warning restore CS1591
