// <auto-generated>
//     This code was generated by GenerateRequestCmdlets.ps1 (version 1.0.0) on 2025-10-09T12:09:15.8712596+00:00.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member

using System;
using System.Text;
using System.Management.Automation;
using Microsoft.Xrm.Sdk;
using Microsoft.Xrm.Sdk.Messages;
using Microsoft.Crm.Sdk.Messages;
using Microsoft.PowerPlatform.Dataverse.Client;
using Rnwood.Dataverse.Data.PowerShell.Commands;

namespace Rnwood.Dataverse.Data.PowerShell.Commands.Sdk
{
    /// <summary>
    /// Contains the data that is needed to create a new customer lookup column, and optionally, to add it to a specified unmanaged solution.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("GenerateRequestCmdlets.ps1", "1.0.0")]
    [System.Diagnostics.DebuggerNonUserCode]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [Cmdlet("Invoke", "DataverseCreateCustomerRelationships", SupportsShouldProcess = true, ConfirmImpact = ConfirmImpact.Medium)]
    public class InvokeDataverseCreateCustomerRelationshipsCmdlet : OrganizationServiceCmdlet
    {

        

        

                /// <summary>
        /// Gets or sets the metadata for the lookup column used to store the ID of the related record. Required.
        /// </summary>

        [Parameter(HelpMessage = "Gets or sets the metadata for the lookup column used to store the ID of the related record. Required.")]
        public Microsoft.Xrm.Sdk.Metadata.LookupAttributeMetadata Lookup { get; set; }

        /// <summary>
        /// Gets or sets the metadata array for the one-to-many relationships to the Account and Contact tables. Required.
        /// </summary>

        [Parameter(HelpMessage = "Gets or sets the metadata array for the one-to-many relationships to the Account and Contact tables. Required.")]
        public Microsoft.Xrm.Sdk.Metadata.OneToManyRelationshipMetadata[] OneToManyRelationships { get; set; }

        /// <summary>
        /// Gets or sets the unique name of the solution you are adding the solution component to. Required.
        /// </summary>

        [Parameter(HelpMessage = "Gets or sets the unique name of the solution you are adding the solution component to. Required.")]
        public System.String SolutionUniqueName { get; set; }

                /// <summary>
        /// Processes the cmdlet request and writes the response to the pipeline.
        /// </summary>
        protected override void ProcessRecord()
        {
            base.ProcessRecord();

            var request = new Microsoft.Xrm.Sdk.Messages.CreateCustomerRelationshipsRequest();
                        request.Lookup = Lookup;
            request.OneToManyRelationships = OneToManyRelationships;
            request.SolutionUniqueName = SolutionUniqueName;

            // Build a short serialized summary of the request for ShouldProcess output
            var requestSummary = new StringBuilder();
            try
            {
                var props = request.GetType().GetProperties(System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.Instance);
                foreach (var p in props)
                {
                    object val = null;
                    try { val = p.GetValue(request); } catch { val = null; }
                    var vstr = val == null ? "null" : val.ToString();
                    requestSummary.Append(p.Name).Append("=").Append(vstr).Append("; ");
                }
            }
            catch
            {
                // Ignore any errors while serializing the request for what-if messaging
            }

            // Emit verbose output of the serialized request when -Verbose is used
            try { WriteVerbose(requestSummary.ToString()); } catch { }

            // Support -WhatIf and -Confirm; include request summary in the action description
            if (!ShouldProcess(request.GetType().Name, requestSummary.ToString()))
            {
                return;
            }

            var response = Connection.Execute(request);
            WriteObject(response);
        }
    }
}

#pragma warning restore CS1591
