// <auto-generated>
//     This code was generated by GenerateRequestCmdlets.ps1 (version 1.0.0) on 2025-10-04T09:09:24.3530647+01:00.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member

using System;
using System.Text;
using System.Management.Automation;
using Microsoft.Xrm.Sdk;
using Microsoft.Xrm.Sdk.Messages;
using Microsoft.Crm.Sdk.Messages;
using Microsoft.PowerPlatform.Dataverse.Client;
using Rnwood.Dataverse.Data.PowerShell.Commands;

namespace Rnwood.Dataverse.Data.PowerShell.Commands.Sdk
{
    /// <summary>
    /// Contains the data needed to export a solution.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("GenerateRequestCmdlets.ps1", "1.0.0")]
    [System.Diagnostics.DebuggerNonUserCode]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [Cmdlet("Invoke", "DataverseExportSolution", SupportsShouldProcess = true, ConfirmImpact = ConfirmImpact.Medium)]
    public class InvokeDataverseExportSolutionCmdlet : OrganizationServiceCmdlet
    {
                /// <summary>
        /// DataverseConnection instance obtained from Get-DataverseConnection cmdlet
        /// </summary>
        [Parameter(Mandatory = true, HelpMessage = "DataverseConnection instance obtained from Get-DataverseConnection cmdlet")]
        public override ServiceClient Connection { get; set; }

        

        

                /// <summary>
        /// Gets or sets the unique name of the solution to be exported. Required.
        /// </summary>

        [Parameter(HelpMessage = "Gets or sets the unique name of the solution to be exported. Required.")]
        public System.String SolutionName { get; set; }

        /// <summary>
        /// Gets or sets whether the solution should be exported as a managed solution. Required.
        /// </summary>

        [Parameter(HelpMessage = "Gets or sets whether the solution should be exported as a managed solution. Required.")]
        public System.Boolean Managed { get; set; }

        /// <summary>
        /// Get or set a value indicating the version that the exported solution will support.
        /// </summary>

        [Parameter(HelpMessage = "Get or set a value indicating the version that the exported solution will support.")]
        public System.String TargetVersion { get; set; }

        /// <summary>
        /// Gets or sets whether auto numbering settings should be included in the solution being exported. Optional.
        /// </summary>

        [Parameter(HelpMessage = "Gets or sets whether auto numbering settings should be included in the solution being exported. Optional.")]
        public System.Boolean ExportAutoNumberingSettings { get; set; }

        /// <summary>
        /// Gets or sets whether calendar settings should be included in the solution being exported. Optional.
        /// </summary>

        [Parameter(HelpMessage = "Gets or sets whether calendar settings should be included in the solution being exported. Optional.")]
        public System.Boolean ExportCalendarSettings { get; set; }

        /// <summary>
        /// Gets or sets whether customization settings should be included in the solution being exported. Optional.
        /// </summary>

        [Parameter(HelpMessage = "Gets or sets whether customization settings should be included in the solution being exported. Optional.")]
        public System.Boolean ExportCustomizationSettings { get; set; }

        /// <summary>
        /// Gets or sets whether email tracking settings should be included in the solution being exported. Optional.
        /// </summary>

        [Parameter(HelpMessage = "Gets or sets whether email tracking settings should be included in the solution being exported. Optional.")]
        public System.Boolean ExportEmailTrackingSettings { get; set; }

        /// <summary>
        /// Gets or sets whether general settings should be included in the solution being exported. Optional.
        /// </summary>

        [Parameter(HelpMessage = "Gets or sets whether general settings should be included in the solution being exported. Optional.")]
        public System.Boolean ExportGeneralSettings { get; set; }

        /// <summary>
        /// Gets or sets whether marketing settings should be included in the solution being exported. Optional.
        /// </summary>

        [Parameter(HelpMessage = "Gets or sets whether marketing settings should be included in the solution being exported. Optional.")]
        public System.Boolean ExportMarketingSettings { get; set; }

        /// <summary>
        /// Gets or sets whether outlook synchronization settings should be included in the solution being exported. Optional.
        /// </summary>

        [Parameter(HelpMessage = "Gets or sets whether outlook synchronization settings should be included in the solution being exported. Optional.")]
        public System.Boolean ExportOutlookSynchronizationSettings { get; set; }

        /// <summary>
        /// Gets or sets whether relationship role settings should be included in the solution being exported. Optional.
        /// </summary>

        [Parameter(HelpMessage = "Gets or sets whether relationship role settings should be included in the solution being exported. Optional.")]
        public System.Boolean ExportRelationshipRoles { get; set; }

        /// <summary>
        /// Gets or sets whether ISV.Config settings should be included in the solution being exported. Optional.
        /// </summary>

        [Parameter(HelpMessage = "Gets or sets whether ISV.Config settings should be included in the solution being exported. Optional.")]
        public System.Boolean ExportIsvConfig { get; set; }

        /// <summary>
        /// Gets or sets whether sales settings should be included in the solution being exported. Optional.
        /// </summary>

        [Parameter(HelpMessage = "Gets or sets whether sales settings should be included in the solution being exported. Optional.")]
        public System.Boolean ExportSales { get; set; }

        /// <summary>
        /// For internal use only.
        /// </summary>

        [Parameter(HelpMessage = "For internal use only.")]
        public System.Boolean ExportExternalApplications { get; set; }

        /// <summary>
        /// Gets or sets whether solution component parameters should be included in the solution being exported. Optional.
        /// </summary>

        [Parameter(HelpMessage = "Gets or sets whether solution component parameters should be included in the solution being exported. Optional.")]
        public Microsoft.Xrm.Sdk.ExportComponentsParams ExportComponentsParams { get; set; }

                /// <summary>
        /// Processes the cmdlet request and writes the response to the pipeline.
        /// </summary>
        protected override void ProcessRecord()
        {
            base.ProcessRecord();

            var request = new Microsoft.Crm.Sdk.Messages.ExportSolutionRequest();
                        request.SolutionName = SolutionName;
            request.Managed = Managed;
            request.TargetVersion = TargetVersion;
            request.ExportAutoNumberingSettings = ExportAutoNumberingSettings;
            request.ExportCalendarSettings = ExportCalendarSettings;
            request.ExportCustomizationSettings = ExportCustomizationSettings;
            request.ExportEmailTrackingSettings = ExportEmailTrackingSettings;
            request.ExportGeneralSettings = ExportGeneralSettings;
            request.ExportMarketingSettings = ExportMarketingSettings;
            request.ExportOutlookSynchronizationSettings = ExportOutlookSynchronizationSettings;
            request.ExportRelationshipRoles = ExportRelationshipRoles;
            request.ExportIsvConfig = ExportIsvConfig;
            request.ExportSales = ExportSales;
            request.ExportExternalApplications = ExportExternalApplications;
            request.ExportComponentsParams = ExportComponentsParams;

            // Build a short serialized summary of the request for ShouldProcess output
            var requestSummary = new StringBuilder();
            try
            {
                var props = request.GetType().GetProperties(System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.Instance);
                foreach (var p in props)
                {
                    object val = null;
                    try { val = p.GetValue(request); } catch { val = null; }
                    var vstr = val == null ? "null" : val.ToString();
                    requestSummary.Append(p.Name).Append("=").Append(vstr).Append("; ");
                }
            }
            catch
            {
                // Ignore any errors while serializing the request for what-if messaging
            }

            // Emit verbose output of the serialized request when -Verbose is used
            try { WriteVerbose(requestSummary.ToString()); } catch { }

            // Support -WhatIf and -Confirm; include request summary in the action description
            if (!ShouldProcess(request.GetType().Name, requestSummary.ToString()))
            {
                return;
            }

            var response = Connection.Execute(request);
            WriteObject(response);
        }
    }
}

#pragma warning restore CS1591
