// <auto-generated>
//     This code was generated by GenerateRequestCmdlets.ps1 (version 1.0.0) on 2025-10-04T16:01:47.8746113+01:00.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member

using System;
using System.Text;
using System.Management.Automation;
using Microsoft.Xrm.Sdk;
using Microsoft.Xrm.Sdk.Messages;
using Microsoft.Crm.Sdk.Messages;
using Microsoft.PowerPlatform.Dataverse.Client;
using Rnwood.Dataverse.Data.PowerShell.Commands;

namespace Rnwood.Dataverse.Data.PowerShell.Commands.Sdk
{
    /// <summary>
    /// Contains the data that is needed to submit an asynchronous system job that detects and logs multiple duplicate records.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("GenerateRequestCmdlets.ps1", "1.0.0")]
    [System.Diagnostics.DebuggerNonUserCode]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [Cmdlet("Invoke", "DataverseBulkDetectDuplicates", SupportsShouldProcess = true, ConfirmImpact = ConfirmImpact.Medium)]
    public class InvokeDataverseBulkDetectDuplicatesCmdlet : OrganizationServiceCmdlet
    {
                /// <summary>

        

        

                /// <summary>
        /// Gets or sets the query representing the metadata to return.
        /// </summary>

        [Parameter(HelpMessage = "Gets or sets the query representing the metadata to return.")]
        public Microsoft.Xrm.Sdk.Query.QueryBase Query { get; set; }

        /// <summary>
        /// Gets or sets the name of an asynchronous bulk delete job. Required.
        /// </summary>

        [Parameter(HelpMessage = "Gets or sets the name of an asynchronous bulk delete job. Required.")]
        public System.String JobName { get; set; }

        /// <summary>
        /// Gets or sets a value that indicates whether an email notification is sent after the bulk delete job has finished running. Required.
        /// </summary>

        [Parameter(HelpMessage = "Gets or sets a value that indicates whether an email notification is sent after the bulk delete job has finished running. Required.")]
        public System.Boolean SendEmailNotification { get; set; }

        /// <summary>
        /// Sets the ID of the template (email template) that is used for the email notification.
        /// </summary>

        [Parameter(HelpMessage = "Sets the ID of the template (email template) that is used for the email notification.")]
        public System.Guid TemplateId { get; set; }

        /// <summary>
        /// Gets or sets an array of IDs for the system users (users) who are listed in the To box of an email notification. Required.
        /// </summary>

        [Parameter(HelpMessage = "Gets or sets an array of IDs for the system users (users) who are listed in the To box of an email notification. Required.")]
        public System.Guid[] ToRecipients { get; set; }

        /// <summary>
        /// Gets or sets an array of IDs for the system users (users) who are listed in the Cc box of the email notification. Required.
        /// </summary>

        [Parameter(HelpMessage = "Gets or sets an array of IDs for the system users (users) who are listed in the Cc box of the email notification. Required.")]
        public System.Guid[] CCRecipients { get; set; }

        /// <summary>
        /// Gets or sets the recurrence pattern for the bulk delete job. Optional.
        /// </summary>

        [Parameter(HelpMessage = "Gets or sets the recurrence pattern for the bulk delete job. Optional.")]
        public System.String RecurrencePattern { get; set; }

        /// <summary>
        /// Gets or sets the start date and time of an asynchronous system job that detects and logs multiple duplicate records. Optional.
        /// </summary>

        [Parameter(HelpMessage = "Gets or sets the start date and time of an asynchronous system job that detects and logs multiple duplicate records. Optional.")]
        public System.DateTime RecurrenceStartTime { get; set; }

                /// <summary>
        /// Processes the cmdlet request and writes the response to the pipeline.
        /// </summary>
        protected override void ProcessRecord()
        {
            base.ProcessRecord();

            var request = new Microsoft.Crm.Sdk.Messages.BulkDetectDuplicatesRequest();
                        request.Query = Query;
            request.JobName = JobName;
            request.SendEmailNotification = SendEmailNotification;
            request.TemplateId = TemplateId;
            request.ToRecipients = ToRecipients;
            request.CCRecipients = CCRecipients;
            request.RecurrencePattern = RecurrencePattern;
            request.RecurrenceStartTime = RecurrenceStartTime;

            // Build a short serialized summary of the request for ShouldProcess output
            var requestSummary = new StringBuilder();
            try
            {
                var props = request.GetType().GetProperties(System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.Instance);
                foreach (var p in props)
                {
                    object val = null;
                    try { val = p.GetValue(request); } catch { val = null; }
                    var vstr = val == null ? "null" : val.ToString();
                    requestSummary.Append(p.Name).Append("=").Append(vstr).Append("; ");
                }
            }
            catch
            {
                // Ignore any errors while serializing the request for what-if messaging
            }

            // Emit verbose output of the serialized request when -Verbose is used
            try { WriteVerbose(requestSummary.ToString()); } catch { }

            // Support -WhatIf and -Confirm; include request summary in the action description
            if (!ShouldProcess(request.GetType().Name, requestSummary.ToString()))
            {
                return;
            }

            var response = Connection.Execute(request);
            WriteObject(response);
        }
    }
}

#pragma warning restore CS1591
