// <auto-generated>
//     This code was generated by GenerateRequestCmdlets.ps1 (version 1.0.0) on 2025-10-04T14:49:22.0308074+01:00.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member

using System;
using System.Text;
using System.Management.Automation;
using Microsoft.Xrm.Sdk;
using Microsoft.Xrm.Sdk.Messages;
using Microsoft.Crm.Sdk.Messages;
using Microsoft.PowerPlatform.Dataverse.Client;
using Rnwood.Dataverse.Data.PowerShell.Commands;

namespace Rnwood.Dataverse.Data.PowerShell.Commands.Sdk
{
    /// <summary>
    /// Contains the data that is needed to perform a full-text search on knowledge articles in CRM using the specified search text.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("GenerateRequestCmdlets.ps1", "1.0.0")]
    [System.Diagnostics.DebuggerNonUserCode]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [Cmdlet("Invoke", "DataverseFullTextSearchKnowledgeArticle", SupportsShouldProcess = true, ConfirmImpact = ConfirmImpact.Medium)]
    public class InvokeDataverseFullTextSearchKnowledgeArticleCmdlet : OrganizationServiceCmdlet
    {
                /// <summary>
        /// DataverseConnection instance obtained from Get-DataverseConnection cmdlet
        /// </summary>
        [Parameter(Mandatory = true, HelpMessage = "DataverseConnection instance obtained from Get-DataverseConnection cmdlet")]
        public override ServiceClient Connection { get; set; }

        

        

                /// <summary>
        /// Gets or sets the text to search for in knowledge articles. Required.
        /// </summary>

        [Parameter(HelpMessage = "Gets or sets the text to search for in knowledge articles. Required.")]
        public System.String SearchText { get; set; }

        /// <summary>
        /// Gets or sets a value that indicates whether to use inflectional stem matching when searching for knowledge articles. Required.
        /// </summary>

        [Parameter(HelpMessage = "Gets or sets a value that indicates whether to use inflectional stem matching when searching for knowledge articles. Required.")]
        public System.Boolean UseInflection { get; set; }

        /// <summary>
        /// Gets or sets a value that indicates whether to remove multiple versions of the same knowledge article in search results. Required.
        /// </summary>

        [Parameter(HelpMessage = "Gets or sets a value that indicates whether to remove multiple versions of the same knowledge article in search results. Required.")]
        public System.Boolean RemoveDuplicates { get; set; }

        /// <summary>
        /// Gets or sets the state of the knowledge articles to filter the search results. Required.
        /// </summary>

        [Parameter(HelpMessage = "Gets or sets the state of the knowledge articles to filter the search results. Required.")]
        public System.Int32 StateCode { get; set; }

        /// <summary>
        /// Gets or sets the query criteria to find knowledge articles with specified text. Required.
        /// </summary>

        [Parameter(HelpMessage = "Gets or sets the query criteria to find knowledge articles with specified text. Required.")]
        public Microsoft.Xrm.Sdk.Query.QueryBase QueryExpression { get; set; }

                /// <summary>
        /// Processes the cmdlet request and writes the response to the pipeline.
        /// </summary>
        protected override void ProcessRecord()
        {
            base.ProcessRecord();

            var request = new Microsoft.Crm.Sdk.Messages.FullTextSearchKnowledgeArticleRequest();
                        request.SearchText = SearchText;
            request.UseInflection = UseInflection;
            request.RemoveDuplicates = RemoveDuplicates;
            request.StateCode = StateCode;
            request.QueryExpression = QueryExpression;

            // Build a short serialized summary of the request for ShouldProcess output
            var requestSummary = new StringBuilder();
            try
            {
                var props = request.GetType().GetProperties(System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.Instance);
                foreach (var p in props)
                {
                    object val = null;
                    try { val = p.GetValue(request); } catch { val = null; }
                    var vstr = val == null ? "null" : val.ToString();
                    requestSummary.Append(p.Name).Append("=").Append(vstr).Append("; ");
                }
            }
            catch
            {
                // Ignore any errors while serializing the request for what-if messaging
            }

            // Emit verbose output of the serialized request when -Verbose is used
            try { WriteVerbose(requestSummary.ToString()); } catch { }

            // Support -WhatIf and -Confirm; include request summary in the action description
            if (!ShouldProcess(request.GetType().Name, requestSummary.ToString()))
            {
                return;
            }

            var response = Connection.Execute(request);
            WriteObject(response);
        }
    }
}

#pragma warning restore CS1591
