// <auto-generated>
//     This code was generated by GenerateRequestCmdlets.ps1 (version 1.0.0) on 2025-10-06T19:48:38.1287085+00:00.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member

using System;
using System.Text;
using System.Management.Automation;
using Microsoft.Xrm.Sdk;
using Microsoft.Xrm.Sdk.Messages;
using Microsoft.Crm.Sdk.Messages;
using Microsoft.PowerPlatform.Dataverse.Client;
using Rnwood.Dataverse.Data.PowerShell.Commands;

namespace Rnwood.Dataverse.Data.PowerShell.Commands.Sdk
{
    /// <summary>
    /// Contains the data that is needed to update an option set value in for a column.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("GenerateRequestCmdlets.ps1", "1.0.0")]
    [System.Diagnostics.DebuggerNonUserCode]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [Cmdlet("Invoke", "DataverseUpdateStateValue", SupportsShouldProcess = true, ConfirmImpact = ConfirmImpact.Medium)]
    public class InvokeDataverseUpdateStateValueCmdlet : OrganizationServiceCmdlet
    {

        

        

                /// <summary>
        /// For internal use only.
        /// </summary>

        [Parameter(HelpMessage = "For internal use only.")]
        public System.String OptionSetName { get; set; }

        /// <summary>
        /// Gets or sets the logical name of the choice column from which to delete the option value. Optional.
        /// </summary>

        [Parameter(HelpMessage = "Gets or sets the logical name of the choice column from which to delete the option value. Optional.")]
        public System.String AttributeLogicalName { get; set; }

        /// <summary>
        /// Gets or sets the logical name of the table that contains the column. Required.
        /// </summary>

        [Parameter(HelpMessage = "Gets or sets the logical name of the table that contains the column. Required.")]
        public System.String EntityLogicalName { get; set; }

        /// <summary>
        /// Gets or sets the value of the option to delete. Required.
        /// </summary>

        [Parameter(HelpMessage = "Gets or sets the value of the option to delete. Required.")]
        public System.Int32 Value { get; set; }

        /// <summary>
        /// Gets or sets the label for the option. Required.
        /// </summary>

        [Parameter(HelpMessage = "Gets or sets the label for the option. Required.")]
        public Microsoft.Xrm.Sdk.Label Label { get; set; }

        /// <summary>
        /// Gets or sets a description for the option. Optional.
        /// </summary>

        [Parameter(HelpMessage = "Gets or sets a description for the option. Optional.")]
        public Microsoft.Xrm.Sdk.Label Description { get; set; }

        /// <summary>
        /// Gets or sets whether the label metadata will be merged or overwritten. Required.
        /// </summary>

        [Parameter(HelpMessage = "Gets or sets whether the label metadata will be merged or overwritten. Required.")]
        public System.Boolean MergeLabels { get; set; }

        /// <summary>
        /// Gets or sets the default value for the statuscode (status reason) column when this statecode value is set. Optional.
        /// </summary>

        [Parameter(HelpMessage = "Gets or sets the default value for the statuscode (status reason) column when this statecode value is set. Optional.")]
        public int? DefaultStatusCode { get; set; }

                /// <summary>
        /// Processes the cmdlet request and writes the response to the pipeline.
        /// </summary>
        protected override void ProcessRecord()
        {
            base.ProcessRecord();

            var request = new Microsoft.Xrm.Sdk.Messages.UpdateStateValueRequest();
                        request.OptionSetName = OptionSetName;
            request.AttributeLogicalName = AttributeLogicalName;
            request.EntityLogicalName = EntityLogicalName;
            request.Value = Value;
            request.Label = Label;
            request.Description = Description;
            request.MergeLabels = MergeLabels;
            request.DefaultStatusCode = DefaultStatusCode;

            // Build a short serialized summary of the request for ShouldProcess output
            var requestSummary = new StringBuilder();
            try
            {
                var props = request.GetType().GetProperties(System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.Instance);
                foreach (var p in props)
                {
                    object val = null;
                    try { val = p.GetValue(request); } catch { val = null; }
                    var vstr = val == null ? "null" : val.ToString();
                    requestSummary.Append(p.Name).Append("=").Append(vstr).Append("; ");
                }
            }
            catch
            {
                // Ignore any errors while serializing the request for what-if messaging
            }

            // Emit verbose output of the serialized request when -Verbose is used
            try { WriteVerbose(requestSummary.ToString()); } catch { }

            // Support -WhatIf and -Confirm; include request summary in the action description
            if (!ShouldProcess(request.GetType().Name, requestSummary.ToString()))
            {
                return;
            }

            var response = Connection.Execute(request);
            WriteObject(response);
        }
    }
}

#pragma warning restore CS1591
