// <auto-generated>
//     This code was generated by GenerateRequestCmdlets.ps1 (version 1.0.0) on 2025-10-30T07:24:53.1437926+00:00.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member

using System;
using System.Text;
using System.Management.Automation;
using Microsoft.Xrm.Sdk;
using Microsoft.Xrm.Sdk.Messages;
using Microsoft.Crm.Sdk.Messages;
using Microsoft.PowerPlatform.Dataverse.Client;
using Rnwood.Dataverse.Data.PowerShell.Commands;

namespace Rnwood.Dataverse.Data.PowerShell.Commands.Sdk
{
    /// <summary>
    /// Contains the data that is needed to retrieve a collection of records that satisfy the specified criteria. The returns a value that can be used with this request at a later time to return information about how schema definitions have changed since the last request.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("GenerateRequestCmdlets.ps1", "1.0.0")]
    [System.Diagnostics.DebuggerNonUserCode]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [Cmdlet("Invoke", "DataverseRetrieveMetadataChanges", SupportsShouldProcess = true, ConfirmImpact = ConfirmImpact.Medium)]
    public class InvokeDataverseRetrieveMetadataChangesCmdlet : OrganizationServiceCmdlet
    {

        

        

                /// <summary>
        /// Gets or sets the query representing the metadata to return.
        /// </summary>

        [Parameter(HelpMessage = "Gets or sets the query representing the metadata to return.")]
        public Microsoft.Xrm.Sdk.Metadata.Query.EntityQueryExpression Query { get; set; }

        /// <summary>
        /// Gets or sets a value to filter what deleted metadata items will be returned.
        /// </summary>

        [Parameter(HelpMessage = "Gets or sets a value to filter what deleted metadata items will be returned.")]
        public Microsoft.Xrm.Sdk.Metadata.Query.DeletedMetadataFilters DeletedMetadataFilters { get; set; }

        /// <summary>
        /// Gets or sets a timestamp value representing when the last request was made.
        /// </summary>

        [Parameter(HelpMessage = "Gets or sets a timestamp value representing when the last request was made.")]
        public System.String ClientVersionStamp { get; set; }

        /// <summary>
        /// For internal use only.
        /// </summary>

        [Parameter(HelpMessage = "For internal use only.")]
        public System.Boolean RetrieveAllSettings { get; set; }

                /// <summary>
        /// Processes the cmdlet request and writes the response to the pipeline.
        /// </summary>
        protected override void ProcessRecord()
        {
            base.ProcessRecord();

            var request = new Microsoft.Xrm.Sdk.Messages.RetrieveMetadataChangesRequest();
                        request.Query = Query;
            request.DeletedMetadataFilters = DeletedMetadataFilters;
            request.ClientVersionStamp = ClientVersionStamp;
            request.RetrieveAllSettings = RetrieveAllSettings;

            // Build a short serialized summary of the request for ShouldProcess output
            var requestSummary = new StringBuilder();
            try
            {
                var props = request.GetType().GetProperties(System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.Instance);
                foreach (var p in props)
                {
                    object val = null;
                    try { val = p.GetValue(request); } catch { val = null; }
                    var vstr = val == null ? "null" : val.ToString();
                    requestSummary.Append(p.Name).Append("=").Append(vstr).Append("; ");
                }
            }
            catch
            {
                // Ignore any errors while serializing the request for what-if messaging
            }

            // Emit verbose output of the serialized request when -Verbose is used
            try { WriteVerbose(requestSummary.ToString()); } catch { }

            // Support -WhatIf and -Confirm; include request summary in the action description
            if (!ShouldProcess(request.GetType().Name, requestSummary.ToString()))
            {
                return;
            }

            var response = Connection.Execute(request);
            WriteObject(response);
        }
    }
}

#pragma warning restore CS1591
