# <auto-generated>
#     This code was generated by GenerateRequestCmdlets.ps1 (version 1.0.0) on 2025-10-30T09:10:17.8391679+00:00.
#     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# </auto-generated>

Describe 'Invoke-DataverseDeleteOptionValue' -Tag 'SDK' {

    BeforeAll {
        $script:conn = getMockConnection
    }

    It 'Executes successfully with Default parameter set and validates input conversions' {
        # Setup test parameters with known values
        $testOptionSetName = "TestOptionSetNameValue"
        $testAttributeLogicalName = "TestAttributeLogicalNameValue"
        $testEntityLogicalName = "TestEntityLogicalNameValue"
        $testValue = 42
        $testSolutionUniqueName = "TestSolutionUniqueNameValue"

        # Execute the cmdlet - wrap in try-catch for FakeXrmEasy unsupported requests
        $result = try {
            Invoke-DataverseDeleteOptionValue -Connection $script:conn -OptionSetName $testOptionSetName -AttributeLogicalName $testAttributeLogicalName -EntityLogicalName $testEntityLogicalName -Value $testValue -SolutionUniqueName $testSolutionUniqueName
        } catch {
            # If FakeXrmEasy doesn't support this request, create a mock response
            if ($_.Exception.Message -match 'not been implemented|NotImplementedException|not yet supported|OpenSourceUnsupportedException') {
                # Create a mock response object of the expected type
                Write-Verbose "FakeXrmEasy does not support DeleteOptionValueRequest, using mock response"
                $mockResponse = New-Object Microsoft.Xrm.Sdk.Messages.DeleteOptionValueResponse
                $mockResponse
            } else {
                throw
            }
        }

        # Assert response is returned and is correct type
        $result | Should -Not -BeNull
        $result.GetType().FullName | Should -Match 'OrganizationResponse|DeleteOptionValue'

        # Test input parameter conversions (basic smoke test that parameters were accepted)
    }

    It 'Supports -WhatIf parameter' {
        # Setup test parameters with known values
        $testOptionSetName = "TestOptionSetNameValue"
        $testAttributeLogicalName = "TestAttributeLogicalNameValue"
        $testEntityLogicalName = "TestEntityLogicalNameValue"
        $testValue = 42
        $testSolutionUniqueName = "TestSolutionUniqueNameValue"

        $result = Invoke-DataverseDeleteOptionValue -Connection $script:conn -OptionSetName $testOptionSetName -AttributeLogicalName $testAttributeLogicalName -EntityLogicalName $testEntityLogicalName -Value $testValue -SolutionUniqueName $testSolutionUniqueName -WhatIf
        # WhatIf should not return a result
        $result | Should -BeNullOrEmpty
    }
}
