# <auto-generated>
#     This code was generated by GenerateRequestCmdlets.ps1 (version 1.0.0) on 2025-10-08T20:29:30.1630983+00:00.
#     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# </auto-generated>

. $PSScriptRoot/../Common.ps1

Describe 'Invoke-DataverseMerge' {

    BeforeAll {
        $script:conn = getMockConnection
    }

    It 'Can invoke the cmdlet with a mock connection' {
        {
            $testEntity = @{ firstname = 'Test'; lastname = 'User' }
            # Create test entity
            # Create test parameters
            $Target = @{ Id = [Guid]::NewGuid(); LogicalName = 'contact' }
            $SubordinateId = [Guid]::NewGuid()
            $UpdateContent = $testEntity
            $PerformParentingChecks = $true

            $result = Invoke-DataverseMerge -Connection $script:conn -Target $Target -SubordinateId $SubordinateId -UpdateContent $UpdateContent -PerformParentingChecks $PerformParentingChecks
            $result | Should -Not -BeNull
        } | Should -Not -Throw
    }

    It 'Supports -WhatIf parameter' {
        {
            # Basic WhatIf test - may need parameter adjustment
            $result = Invoke-DataverseMerge -Connection $script:conn -WhatIf
        } | Should -Not -Throw
    }
}
