# <auto-generated>
#     This code was generated by GenerateRequestCmdlets.ps1 (version 1.0.0) on 2025-10-08T21:02:58.5667477+00:00.
#     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# </auto-generated>

. $PSScriptRoot/../Common.ps1

Describe 'Invoke-DataverseStageAndUpgradeAsync' -Tag 'SDK' {

    BeforeAll {
        $script:conn = getMockConnection
    }

    It 'Executes successfully with Default parameter set' {
        # Setup test parameters with known values
        $testOverwriteUnmanagedCustomizations = $true
        $testPublishWorkflows = $true
        $testCustomizationFile = [System.Text.Encoding]::UTF8.GetBytes('TestDataCustomizationFile')
        $testImportJobId = [Guid]::Parse('12345678-1234-1234-1234-123456789012')
        $testConvertToManaged = $true
        $testSkipProductUpdateDependencies = $true
        $testSkipQueueRibbonJob = $true
        $testAsyncRibbonProcessing = $true

        $result = Invoke-DataverseStageAndUpgradeAsync -Connection $script:conn -OverwriteUnmanagedCustomizations $testOverwriteUnmanagedCustomizations -PublishWorkflows $testPublishWorkflows -CustomizationFile $testCustomizationFile -ImportJobId $testImportJobId -ConvertToManaged $testConvertToManaged -SkipProductUpdateDependencies $testSkipProductUpdateDependencies -SkipQueueRibbonJob $testSkipQueueRibbonJob -AsyncRibbonProcessing $testAsyncRibbonProcessing

        # Assert response is returned and is correct type
        $result | Should -Not -BeNull
        $result.GetType().FullName | Should -Match 'OrganizationResponse|StageAndUpgradeAsync'
    }

    It 'Executes successfully with FromFile parameter set' {
        # Create a temporary test file
        $testFilePath = [System.IO.Path]::GetTempFileName()
        $testData = 'TestFileDataForByteArray'
        [System.IO.File]::WriteAllText($testFilePath, $testData)

        try {
            # Setup test parameters with known values
            $testOverwriteUnmanagedCustomizations = $true
            $testPublishWorkflows = $true
            $testImportJobId = [Guid]::Parse('12345678-1234-1234-1234-123456789012')
            $testConvertToManaged = $true
            $testSkipProductUpdateDependencies = $true
            $testSkipQueueRibbonJob = $true
            $testAsyncRibbonProcessing = $true

            $result = Invoke-DataverseStageAndUpgradeAsync -Connection $script:conn -OverwriteUnmanagedCustomizations $testOverwriteUnmanagedCustomizations -PublishWorkflows $testPublishWorkflows -ImportJobId $testImportJobId -ConvertToManaged $testConvertToManaged -SkipProductUpdateDependencies $testSkipProductUpdateDependencies -SkipQueueRibbonJob $testSkipQueueRibbonJob -AsyncRibbonProcessing $testAsyncRibbonProcessing -InFile $testFilePath

            # Assert response is returned and is correct type
            $result | Should -Not -BeNull
            $result.GetType().FullName | Should -Match 'OrganizationResponse|StageAndUpgradeAsync'
        } finally {
            if (Test-Path $testFilePath) {
                Remove-Item $testFilePath -Force
            }
        }
    }

}
