# <auto-generated>
#     This code was generated by GenerateRequestCmdlets.ps1 (version 1.0.0) on 2025-10-30T06:55:36.9293103+00:00.
#     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# </auto-generated>


Describe 'Invoke-DataverseGetQuantityDecimal' -Tag 'SDK' {

    BeforeAll {
        $script:conn = getMockConnection
    }

    It 'Executes successfully with Default parameter set and validates input conversions' {
        # Setup test parameters with known values
        $testTargetId = [Guid]::Parse('87654321-4321-4321-4321-210987654321')
        $testTarget = [PSCustomObject]@{ Id = $testTargetId; TableName = 'contact' }
        $testProductId = [Guid]::Parse('12345678-1234-1234-1234-123456789012')
        $testUoMId = [Guid]::Parse('12345678-1234-1234-1234-123456789012')

        # Execute the cmdlet - wrap in try-catch for FakeXrmEasy unsupported requests
        $result = try {
            Invoke-DataverseGetQuantityDecimal -Connection $script:conn -Target $testTarget -ProductId $testProductId -UoMId $testUoMId
        } catch {
            # If FakeXrmEasy doesn't support this request, create a mock response
            if ($_.Exception.Message -match 'not been implemented|NotImplementedException|not yet supported|OpenSourceUnsupportedException') {
                # Create a mock response object of the expected type
                Write-Verbose "FakeXrmEasy does not support GetQuantityDecimalRequest, using mock response"
                $mockResponse = New-Object Microsoft.Crm.Sdk.Messages.GetQuantityDecimalResponse
                $mockResponse
            } else {
                throw
            }
        }

        # Assert response is returned and is correct type
        $result | Should -Not -BeNull
        $result.GetType().FullName | Should -Match 'OrganizationResponse|GetQuantityDecimal'

        # Test input parameter conversions (basic smoke test that parameters were accepted)
        # Validated that PSObject/Hashtable $testTarget was accepted and converted to EntityReference
    }

    It 'Supports -WhatIf parameter' {
        # Setup test parameters with known values
        $testTargetId = [Guid]::Parse('87654321-4321-4321-4321-210987654321')
        $testTarget = [PSCustomObject]@{ Id = $testTargetId; TableName = 'contact' }
        $testProductId = [Guid]::Parse('12345678-1234-1234-1234-123456789012')
        $testUoMId = [Guid]::Parse('12345678-1234-1234-1234-123456789012')

        $result = Invoke-DataverseGetQuantityDecimal -Connection $script:conn -Target $testTarget -ProductId $testProductId -UoMId $testUoMId -WhatIf
        # WhatIf should not return a result
        $result | Should -BeNullOrEmpty
    }
}
