# <auto-generated>
#     This code was generated by GenerateRequestCmdlets.ps1 (version 1.0.0) on 2025-10-08T20:30:23.8218364+00:00.
#     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# </auto-generated>

. $PSScriptRoot/../Common.ps1

Describe 'Invoke-DataverseAddSolutionComponent' {

    BeforeAll {
        $script:conn = getMockConnection
    }

    It 'Can invoke the cmdlet with a mock connection' {
        {
            # Create test parameters
            $ComponentId = [Guid]::NewGuid()
            $ComponentType = 1
            $SolutionUniqueName = "TestSolutionUniqueName"
            $AddRequiredComponents = $true
            $DoNotIncludeSubcomponents = $true

            $result = Invoke-DataverseAddSolutionComponent -Connection $script:conn -ComponentId $ComponentId -ComponentType $ComponentType -SolutionUniqueName $SolutionUniqueName -AddRequiredComponents $AddRequiredComponents -DoNotIncludeSubcomponents $DoNotIncludeSubcomponents -IncludedComponentSettingsValues $IncludedComponentSettingsValues
            $result | Should -Not -BeNull
        } | Should -Not -Throw
    }

    It 'Supports -WhatIf parameter' {
        {
            # Basic WhatIf test - may need parameter adjustment
            $result = Invoke-DataverseAddSolutionComponent -Connection $script:conn -WhatIf
        } | Should -Not -Throw
    }
}
