# <auto-generated>
#     This code was generated by GenerateRequestCmdlets.ps1 (version 1.0.0) on 2025-10-08T21:01:46.2570476+00:00.
#     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# </auto-generated>

. $PSScriptRoot/../Common.ps1

Describe 'Invoke-DataverseFullTextSearchKnowledgeArticle' -Tag 'SDK' {

    BeforeAll {
        $script:conn = getMockConnection
    }

    It 'Executes successfully with Default parameter set' {
        # Setup test parameters with known values
        $testSearchText = "TestSearchTextValue"
        $testUseInflection = $true
        $testRemoveDuplicates = $true
        $testStateCode = 42
        $testQueryExpression = New-Object Microsoft.Xrm.Sdk.Query.QueryExpression('contact')

        $result = Invoke-DataverseFullTextSearchKnowledgeArticle -Connection $script:conn -SearchText $testSearchText -UseInflection $testUseInflection -RemoveDuplicates $testRemoveDuplicates -StateCode $testStateCode -QueryExpression $testQueryExpression

        # Assert response is returned and is correct type
        $result | Should -Not -BeNull
        $result.GetType().FullName | Should -Match 'OrganizationResponse|FullTextSearchKnowledgeArticle'
    }

}
