# <auto-generated>
#     This code was generated by GenerateRequestCmdlets.ps1 (version 1.0.0) on 2025-10-08T20:29:34.9156761+00:00.
#     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# </auto-generated>

. $PSScriptRoot/../Common.ps1

Describe 'Invoke-DataversePublishDuplicateRule' {

    BeforeAll {
        $script:conn = getMockConnection
    }

    It 'Can invoke the cmdlet with a mock connection' {
        {
            # Create test parameters
            $DuplicateRuleId = [Guid]::NewGuid()

            $result = Invoke-DataversePublishDuplicateRule -Connection $script:conn -DuplicateRuleId $DuplicateRuleId
            $result | Should -Not -BeNull
        } | Should -Not -Throw
    }

    It 'Supports -WhatIf parameter' {
        {
            # Basic WhatIf test - may need parameter adjustment
            $result = Invoke-DataversePublishDuplicateRule -Connection $script:conn -WhatIf
        } | Should -Not -Throw
    }
}
