# <auto-generated>
#     This code was generated by GenerateRequestCmdlets.ps1 (version 1.0.0) on 2025-10-08T20:30:01.6824139+00:00.
#     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# </auto-generated>

. $PSScriptRoot/../Common.ps1

Describe 'Invoke-DataverseSyncBulkOperation' {

    BeforeAll {
        $script:conn = getMockConnection
    }

    It 'Can invoke the cmdlet with a mock connection' {
        {
            # Create test parameters
            $QuerySet = New-Object Microsoft.Xrm.Sdk.Query.QueryExpression('contact')
            $OperationType = 1

            $result = Invoke-DataverseSyncBulkOperation -Connection $script:conn -QuerySet $QuerySet -OperationType $OperationType
            $result | Should -Not -BeNull
        } | Should -Not -Throw
    }

    It 'Supports -WhatIf parameter' {
        {
            # Basic WhatIf test - may need parameter adjustment
            $result = Invoke-DataverseSyncBulkOperation -Connection $script:conn -WhatIf
        } | Should -Not -Throw
    }
}
