# <auto-generated>
#     This code was generated by GenerateRequestCmdlets.ps1 (version 1.0.0) on 2025-10-09T12:08:19.7501512+00:00.
#     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# </auto-generated>

. $PSScriptRoot/../Common.ps1

Describe 'Invoke-DataverseCloneAsSolution' -Tag 'SDK' {

    BeforeAll {
        $script:conn = getMockConnection
    }

    It 'Executes successfully with Default parameter set and validates input conversions' {
        # Setup test parameters with known values
        $testParentSolutionUniqueName = "TestParentSolutionUniqueNameValue"
        $testDisplayName = "TestDisplayNameValue"
        $testVersionNumber = "TestVersionNumberValue"

        # Execute the cmdlet - wrap in try-catch for FakeXrmEasy unsupported requests
        $result = try {
            Invoke-DataverseCloneAsSolution -Connection $script:conn -ParentSolutionUniqueName $testParentSolutionUniqueName -DisplayName $testDisplayName -VersionNumber $testVersionNumber
        } catch {
            # If FakeXrmEasy doesn't support this request, create a mock response
            if ($_.Exception.Message -match 'not been implemented|NotImplementedException') {
                # Create a mock response object of the expected type
                Write-Verbose "FakeXrmEasy does not support CloneAsSolutionRequest, using mock response"
                $mockResponse = New-Object Microsoft.Crm.Sdk.Messages.CloneAsSolutionResponse
                $mockResponse
            } else {
                throw
            }
        }

        # Assert response is returned and is correct type
        $result | Should -Not -BeNull
        $result.GetType().FullName | Should -Match 'OrganizationResponse|CloneAsSolution'

        # Test input parameter conversions (basic smoke test that parameters were accepted)
    }

    It 'Supports -WhatIf parameter' {
        # Setup test parameters with known values
        $testParentSolutionUniqueName = "TestParentSolutionUniqueNameValue"
        $testDisplayName = "TestDisplayNameValue"
        $testVersionNumber = "TestVersionNumberValue"

        $result = Invoke-DataverseCloneAsSolution -Connection $script:conn -ParentSolutionUniqueName $testParentSolutionUniqueName -DisplayName $testDisplayName -VersionNumber $testVersionNumber -WhatIf
        # WhatIf should not return a result
        $result | Should -BeNullOrEmpty
    }
}
