# <auto-generated>
#     This code was generated by GenerateRequestCmdlets.ps1 (version 1.0.0) on 2025-10-08T21:03:15.2801419+00:00.
#     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# </auto-generated>

. $PSScriptRoot/../Common.ps1

Describe 'Invoke-DataverseRetrieveAttribute' -Tag 'SDK' {

    BeforeAll {
        $script:conn = getMockConnection
    }

    It 'Executes successfully with Default parameter set' {
        # Setup test parameters with known values
        $testEntityLogicalName = "TestEntityLogicalNameValue"
        $testLogicalName = "TestLogicalNameValue"
        $testColumnNumber = 42
        $testMetadataId = [Guid]::Parse('12345678-1234-1234-1234-123456789012')
        $testRetrieveAsIfPublished = $true

        $result = Invoke-DataverseRetrieveAttribute -Connection $script:conn -EntityLogicalName $testEntityLogicalName -LogicalName $testLogicalName -ColumnNumber $testColumnNumber -MetadataId $testMetadataId -RetrieveAsIfPublished $testRetrieveAsIfPublished

        # Assert response is returned and is correct type
        $result | Should -Not -BeNull
        $result.GetType().FullName | Should -Match 'OrganizationResponse|RetrieveAttribute'
    }

}
