# <auto-generated>
#     This code was generated by GenerateRequestCmdlets.ps1 (version 1.0.0) on 2025-10-08T20:30:59.8538787+00:00.
#     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# </auto-generated>

. $PSScriptRoot/../Common.ps1

Describe 'Invoke-DataverseRetrieveByResourceResourceGroup' {

    BeforeAll {
        $script:conn = getMockConnection
    }

    It 'Can invoke the cmdlet with a mock connection' {
        {
            # Create test parameters
            $ResourceId = [Guid]::NewGuid()
            $Query = New-Object Microsoft.Xrm.Sdk.Query.QueryExpression('contact')

            $result = Invoke-DataverseRetrieveByResourceResourceGroup -Connection $script:conn -ResourceId $ResourceId -Query $Query
            $result | Should -Not -BeNull
        } | Should -Not -Throw
    }

    It 'Supports -WhatIf parameter' {
        {
            # Basic WhatIf test - may need parameter adjustment
            $result = Invoke-DataverseRetrieveByResourceResourceGroup -Connection $script:conn -WhatIf
        } | Should -Not -Throw
    }
}
