# <auto-generated>
#     This code was generated by GenerateRequestCmdlets.ps1 (version 1.0.0) on 2025-10-30T08:36:03.2857258+00:00.
#     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# </auto-generated>

Describe 'Invoke-DataverseAssociate' -Tag 'SDK' {

    BeforeAll {
        $script:conn = getMockConnection
    }

    It 'Executes successfully with Default parameter set and validates input conversions' {
        # Setup test parameters with known values
        $testTargetId = [Guid]::Parse('87654321-4321-4321-4321-210987654321')
        $testTarget = [PSCustomObject]@{ Id = $testTargetId; TableName = 'contact' }
        $testRelationship = New-Object Microsoft.Xrm.Sdk.Relationship('contact_account')
        $entityRefCollection = New-Object Microsoft.Xrm.Sdk.EntityReferenceCollection
        $entityRef = New-Object Microsoft.Xrm.Sdk.EntityReference('contact', [Guid]::NewGuid())
        $entityRefCollection.Add($entityRef)
        $testRelatedEntities = $entityRefCollection

        # Execute the cmdlet - wrap in try-catch for FakeXrmEasy unsupported requests
        $result = try {
            Invoke-DataverseAssociate -Connection $script:conn -Target $testTarget -Relationship $testRelationship -RelatedEntities $testRelatedEntities
        } catch {
            # If FakeXrmEasy doesn't support this request, create a mock response
            if ($_.Exception.Message -match 'not been implemented|NotImplementedException|not yet supported|OpenSourceUnsupportedException') {
                # Create a mock response object of the expected type
                Write-Verbose "FakeXrmEasy does not support AssociateRequest, using mock response"
                $mockResponse = New-Object Microsoft.Xrm.Sdk.Messages.AssociateResponse
                $mockResponse
            } else {
                throw
            }
        }

        # Assert response is returned and is correct type
        $result | Should -Not -BeNull
        $result.GetType().FullName | Should -Match 'OrganizationResponse|Associate'

        # Test input parameter conversions (basic smoke test that parameters were accepted)
        # Validated that PSObject/Hashtable $testTarget was accepted and converted to EntityReference
    }

    It 'Supports -WhatIf parameter' {
        # Setup test parameters with known values
        $testTargetId = [Guid]::Parse('87654321-4321-4321-4321-210987654321')
        $testTarget = [PSCustomObject]@{ Id = $testTargetId; TableName = 'contact' }
        $testRelationship = New-Object Microsoft.Xrm.Sdk.Relationship('contact_account')
        $entityRefCollection = New-Object Microsoft.Xrm.Sdk.EntityReferenceCollection
        $entityRef = New-Object Microsoft.Xrm.Sdk.EntityReference('contact', [Guid]::NewGuid())
        $entityRefCollection.Add($entityRef)
        $testRelatedEntities = $entityRefCollection

        $result = Invoke-DataverseAssociate -Connection $script:conn -Target $testTarget -Relationship $testRelationship -RelatedEntities $testRelatedEntities -WhatIf
        # WhatIf should not return a result
        $result | Should -BeNullOrEmpty
    }
}
