# <auto-generated>
#     This code was generated by GenerateRequestCmdlets.ps1 (version 1.0.0) on 2025-10-08T20:30:43.7338583+00:00.
#     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# </auto-generated>

. $PSScriptRoot/../Common.ps1

Describe 'Invoke-DataversePropagateByExpression' {

    BeforeAll {
        $script:conn = getMockConnection
    }

    It 'Can invoke the cmdlet with a mock connection' {
        {
            $testEntity = @{ firstname = 'Test'; lastname = 'User' }
            # Create test entity
            # Create test parameters
            $QueryExpression = New-Object Microsoft.Xrm.Sdk.Query.QueryExpression('contact')
            $FriendlyName = "TestFriendlyName"
            $ExecuteImmediately = $true
            $Activity = $testEntity
            $TemplateId = [Guid]::NewGuid()
            $PostWorkflowEvent = $true
            $Owner = @{ Id = [Guid]::NewGuid(); LogicalName = 'contact' }
            $SendEmail = $true
            $QueueId = [Guid]::NewGuid()

            $result = Invoke-DataversePropagateByExpression -Connection $script:conn -QueryExpression $QueryExpression -FriendlyName $FriendlyName -ExecuteImmediately $ExecuteImmediately -Activity $Activity -TemplateId $TemplateId -PostWorkflowEvent $PostWorkflowEvent -Owner $Owner -SendEmail $SendEmail -QueueId $QueueId
            $result | Should -Not -BeNull
        } | Should -Not -Throw
    }

    It 'Supports -WhatIf parameter' {
        {
            # Basic WhatIf test - may need parameter adjustment
            $result = Invoke-DataversePropagateByExpression -Connection $script:conn -WhatIf
        } | Should -Not -Throw
    }
}
