# <auto-generated>
#     This code was generated by GenerateRequestCmdlets.ps1 (version 1.0.0) on 2025-10-30T06:55:42.5074245+00:00.
#     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# </auto-generated>


Describe 'Invoke-DataverseValidate' -Tag 'SDK' {

    BeforeAll {
        $script:conn = getMockConnection
    }

    It 'Supports -WhatIf parameter' {
        $result = Invoke-DataverseValidate -Connection $script:conn -WhatIf
        # WhatIf should not return a result
        $result | Should -BeNullOrEmpty
    }
}
