# <auto-generated>
#     This code was generated by GenerateRequestCmdlets.ps1 (version 1.0.0) on 2025-10-08T20:30:14.4722199+00:00.
#     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# </auto-generated>

. $PSScriptRoot/../Common.ps1

Describe 'Invoke-DataverseFormatAddress' {

    BeforeAll {
        $script:conn = getMockConnection
    }

    It 'Can invoke the cmdlet with a mock connection' {
        {
            # Create test parameters
            $Line1 = "TestLine1"
            $City = "TestCity"
            $StateOrProvince = "TestStateOrProvince"
            $PostalCode = "TestPostalCode"
            $Country = "TestCountry"

            $result = Invoke-DataverseFormatAddress -Connection $script:conn -Line1 $Line1 -City $City -StateOrProvince $StateOrProvince -PostalCode $PostalCode -Country $Country
            $result | Should -Not -BeNull
        } | Should -Not -Throw
    }

    It 'Supports -WhatIf parameter' {
        {
            # Basic WhatIf test - may need parameter adjustment
            $result = Invoke-DataverseFormatAddress -Connection $script:conn -WhatIf
        } | Should -Not -Throw
    }
}
