# <auto-generated>
#     This code was generated by GenerateRequestCmdlets.ps1 (version 1.0.0) on 2025-10-08T20:29:32.6031217+00:00.
#     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# </auto-generated>

. $PSScriptRoot/../Common.ps1

Describe 'Invoke-DataverseSendTemplate' {

    BeforeAll {
        $script:conn = getMockConnection
    }

    It 'Can invoke the cmdlet with a mock connection' {
        {
            # Create test parameters
            $TemplateId = [Guid]::NewGuid()
            $Sender = @{ Id = [Guid]::NewGuid(); LogicalName = 'contact' }
            $RecipientType = "TestRecipientType"
            $RegardingType = "TestRegardingType"
            $RegardingId = [Guid]::NewGuid()

            $result = Invoke-DataverseSendTemplate -Connection $script:conn -TemplateId $TemplateId -Sender $Sender -RecipientType $RecipientType -RecipientIds $RecipientIds -RegardingType $RegardingType -RegardingId $RegardingId
            $result | Should -Not -BeNull
        } | Should -Not -Throw
    }

    It 'Supports -WhatIf parameter' {
        {
            # Basic WhatIf test - may need parameter adjustment
            $result = Invoke-DataverseSendTemplate -Connection $script:conn -WhatIf
        } | Should -Not -Throw
    }
}
