# <auto-generated>
#     This code was generated by GenerateRequestCmdlets.ps1 (version 1.0.0) on 2025-10-09T12:32:41.2534824+00:00.
#     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# </auto-generated>


Describe 'Invoke-DataverseAddItemCampaign' -Tag 'SDK' {

    BeforeAll {
        $script:conn = getMockConnection
    }

    It 'Executes successfully with Default parameter set and validates input conversions' {
        # Setup test parameters with known values
        $testCampaignId = [Guid]::Parse('12345678-1234-1234-1234-123456789012')
        $testEntityId = [Guid]::Parse('12345678-1234-1234-1234-123456789012')
        $testEntityName = "TestEntityNameValue"

        # Execute the cmdlet - wrap in try-catch for FakeXrmEasy unsupported requests
        $result = try {
            Invoke-DataverseAddItemCampaign -Connection $script:conn -CampaignId $testCampaignId -EntityId $testEntityId -EntityName $testEntityName
        } catch {
            # If FakeXrmEasy doesn't support this request, create a mock response
            if ($_.Exception.Message -match 'not been implemented|NotImplementedException') {
                # Create a mock response object of the expected type
                Write-Verbose "FakeXrmEasy does not support AddItemCampaignRequest, using mock response"
                $mockResponse = New-Object Microsoft.Crm.Sdk.Messages.AddItemCampaignResponse
                $mockResponse
            } else {
                throw
            }
        }

        # Assert response is returned and is correct type
        $result | Should -Not -BeNull
        $result.GetType().FullName | Should -Match 'OrganizationResponse|AddItemCampaign'

        # Test input parameter conversions (basic smoke test that parameters were accepted)
    }

    It 'Supports -WhatIf parameter' {
        # Setup test parameters with known values
        $testCampaignId = [Guid]::Parse('12345678-1234-1234-1234-123456789012')
        $testEntityId = [Guid]::Parse('12345678-1234-1234-1234-123456789012')
        $testEntityName = "TestEntityNameValue"

        $result = Invoke-DataverseAddItemCampaign -Connection $script:conn -CampaignId $testCampaignId -EntityId $testEntityId -EntityName $testEntityName -WhatIf
        # WhatIf should not return a result
        $result | Should -BeNullOrEmpty
    }
}
