# <auto-generated>
#     This code was generated by GenerateRequestCmdlets.ps1 (version 1.0.0) on 2025-10-30T07:47:26.7011867+00:00.
#     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# </auto-generated>

Describe 'Invoke-DataverseExecuteTransaction' -Tag 'SDK' {

    BeforeAll {
        $script:conn = getMockConnection
    }

    It 'Supports -WhatIf parameter' {
        $result = Invoke-DataverseExecuteTransaction -Connection $script:conn -WhatIf
        # WhatIf should not return a result
        $result | Should -BeNullOrEmpty
    }
}
