# <auto-generated>
#     This code was generated by GenerateRequestCmdlets.ps1 (version 1.0.0) on 2025-10-08T21:02:23.9102561+00:00.
#     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# </auto-generated>

. $PSScriptRoot/../Common.ps1

Describe 'Invoke-DataverseAssign' -Tag 'SDK' {

    BeforeAll {
        $script:conn = getMockConnection
    }

    It 'Executes successfully with Default parameter set' {
        # Setup test parameters with known values
        $testTargetId = [Guid]::Parse('87654321-4321-4321-4321-210987654321')
        $testTarget = @{ Id = $testTargetId; LogicalName = 'contact' }
        $testAssigneeId = [Guid]::Parse('87654321-4321-4321-4321-210987654321')
        $testAssignee = @{ Id = $testAssigneeId; LogicalName = 'contact' }

        $result = Invoke-DataverseAssign -Connection $script:conn -Target $testTarget -Assignee $testAssignee

        # Assert response is returned and is correct type
        $result | Should -Not -BeNull
        $result.GetType().FullName | Should -Match 'OrganizationResponse|Assign'
    }

}
