# <auto-generated>
#     This code was generated by GenerateRequestCmdlets.ps1 (version 1.0.0) on 2025-10-08T20:30:06.8746414+00:00.
#     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# </auto-generated>

. $PSScriptRoot/../Common.ps1

Describe 'Invoke-DataverseUpdateRibbonClientMetadata' {

    BeforeAll {
        $script:conn = getMockConnection
    }

    It 'Can invoke the cmdlet with a mock connection' {
        {
            # No parameters required for this cmdlet
            $result = Invoke-DataverseUpdateRibbonClientMetadata -Connection $script:conn
            $result | Should -Not -BeNull
        } | Should -Not -Throw
    }

    It 'Supports -WhatIf parameter' {
        {
            $result = Invoke-DataverseUpdateRibbonClientMetadata -Connection $script:conn -WhatIf
        } | Should -Not -Throw
    }
}
