# <auto-generated>
#     This code was generated by GenerateRequestCmdlets.ps1 (version 1.0.0) on 2025-10-30T07:47:14.7526702+00:00.
#     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# </auto-generated>

Describe 'Invoke-DataverseReactivateEntityKey' -Tag 'SDK' {

    BeforeAll {
        $script:conn = getMockConnection
    }

    It 'Executes successfully with Default parameter set and validates input conversions' {
        # Setup test parameters with known values
        $testEntityKeyLogicalName = "TestEntityKeyLogicalNameValue"
        $testEntityLogicalName = "TestEntityLogicalNameValue"

        # Execute the cmdlet - wrap in try-catch for FakeXrmEasy unsupported requests
        $result = try {
            Invoke-DataverseReactivateEntityKey -Connection $script:conn -EntityKeyLogicalName $testEntityKeyLogicalName -EntityLogicalName $testEntityLogicalName
        } catch {
            # If FakeXrmEasy doesn't support this request, create a mock response
            if ($_.Exception.Message -match 'not been implemented|NotImplementedException|not yet supported|OpenSourceUnsupportedException') {
                # Create a mock response object of the expected type
                Write-Verbose "FakeXrmEasy does not support ReactivateEntityKeyRequest, using mock response"
                $mockResponse = New-Object Microsoft.Xrm.Sdk.Messages.ReactivateEntityKeyResponse
                $mockResponse
            } else {
                throw
            }
        }

        # Assert response is returned and is correct type
        $result | Should -Not -BeNull
        $result.GetType().FullName | Should -Match 'OrganizationResponse|ReactivateEntityKey'

        # Test input parameter conversions (basic smoke test that parameters were accepted)
    }

    It 'Supports -WhatIf parameter' {
        # Setup test parameters with known values
        $testEntityKeyLogicalName = "TestEntityKeyLogicalNameValue"
        $testEntityLogicalName = "TestEntityLogicalNameValue"

        $result = Invoke-DataverseReactivateEntityKey -Connection $script:conn -EntityKeyLogicalName $testEntityKeyLogicalName -EntityLogicalName $testEntityLogicalName -WhatIf
        # WhatIf should not return a result
        $result | Should -BeNullOrEmpty
    }
}
