# <auto-generated>
#     This code was generated by GenerateRequestCmdlets.ps1 (version 1.0.0) on 2025-10-08T20:30:27.9883906+00:00.
#     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# </auto-generated>

. $PSScriptRoot/../Common.ps1

Describe 'Invoke-DataverseAddUserToRecordTeam' {

    BeforeAll {
        $script:conn = getMockConnection
    }

    It 'Can invoke the cmdlet with a mock connection' {
        {
            # Create test parameters
            $Record = @{ Id = [Guid]::NewGuid(); LogicalName = 'contact' }
            $TeamTemplateId = [Guid]::NewGuid()
            $SystemUserId = [Guid]::NewGuid()

            $result = Invoke-DataverseAddUserToRecordTeam -Connection $script:conn -Record $Record -TeamTemplateId $TeamTemplateId -SystemUserId $SystemUserId
            $result | Should -Not -BeNull
        } | Should -Not -Throw
    }

    It 'Supports -WhatIf parameter' {
        {
            # Basic WhatIf test - may need parameter adjustment
            $result = Invoke-DataverseAddUserToRecordTeam -Connection $script:conn -WhatIf
        } | Should -Not -Throw
    }
}
