# <auto-generated>
#     This code was generated by GenerateRequestCmdlets.ps1 (version 1.0.0) on 2025-10-30T06:55:22.6283727+00:00.
#     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# </auto-generated>


Describe 'Invoke-DataverseDeliverImmediatePromoteEmail' -Tag 'SDK' {

    BeforeAll {
        $script:conn = getMockConnection
    }

    It 'Executes successfully with Default parameter set and validates input conversions' {
        # Setup test parameters with known values
        $testEmailId = [Guid]::Parse('12345678-1234-1234-1234-123456789012')
        $testMessageId = "TestMessageIdValue"
        $testSubject = "TestSubjectValue"
        $testFrom = "TestFromValue"
        $testTo = "TestToValue"
        $testCc = "TestCcValue"
        $testBcc = "TestBccValue"
        $testSubmittedBy = "TestSubmittedByValue"
        $testImportance = "TestImportanceValue"
        $testBody = "TestBodyValue"
        $testEWSUrl = "TestEWSUrlValue"
        $testAttachmentToken = "TestAttachmentTokenValue"
        $testExtraProperties = @{ firstname = 'TestFirst'; lastname = 'TestLast'; contactid = [Guid]::NewGuid() }

        # Execute the cmdlet - wrap in try-catch for FakeXrmEasy unsupported requests
        $result = try {
            Invoke-DataverseDeliverImmediatePromoteEmail -Connection $script:conn -EmailId $testEmailId -MessageId $testMessageId -Subject $testSubject -From $testFrom -To $testTo -Cc $testCc -Bcc $testBcc -SubmittedBy $testSubmittedBy -Importance $testImportance -Body $testBody -EWSUrl $testEWSUrl -AttachmentToken $testAttachmentToken -ExtraProperties $testExtraProperties -ExtraPropertiesTableName 'contact'
        } catch {
            # If FakeXrmEasy doesn't support this request, create a mock response
            if ($_.Exception.Message -match 'not been implemented|NotImplementedException|not yet supported|OpenSourceUnsupportedException') {
                # Create a mock response object of the expected type
                Write-Verbose "FakeXrmEasy does not support DeliverImmediatePromoteEmailRequest, using mock response"
                $mockResponse = New-Object Microsoft.Crm.Sdk.Messages.DeliverImmediatePromoteEmailResponse
                $mockResponse
            } else {
                throw
            }
        }

        # Assert response is returned and is correct type
        $result | Should -Not -BeNull
        $result.GetType().FullName | Should -Match 'OrganizationResponse|DeliverImmediatePromoteEmail'

        # Test input parameter conversions (basic smoke test that parameters were accepted)
        # Validated that PSObject $testExtraProperties was accepted and converted to Entity
    }

    It 'Supports -WhatIf parameter' {
        # Setup test parameters with known values
        $testEmailId = [Guid]::Parse('12345678-1234-1234-1234-123456789012')
        $testMessageId = "TestMessageIdValue"
        $testSubject = "TestSubjectValue"
        $testFrom = "TestFromValue"
        $testTo = "TestToValue"
        $testCc = "TestCcValue"
        $testBcc = "TestBccValue"
        $testSubmittedBy = "TestSubmittedByValue"
        $testImportance = "TestImportanceValue"
        $testBody = "TestBodyValue"
        $testEWSUrl = "TestEWSUrlValue"
        $testAttachmentToken = "TestAttachmentTokenValue"
        $testExtraProperties = @{ firstname = 'TestFirst'; lastname = 'TestLast'; contactid = [Guid]::NewGuid() }

        $result = Invoke-DataverseDeliverImmediatePromoteEmail -Connection $script:conn -EmailId $testEmailId -MessageId $testMessageId -Subject $testSubject -From $testFrom -To $testTo -Cc $testCc -Bcc $testBcc -SubmittedBy $testSubmittedBy -Importance $testImportance -Body $testBody -EWSUrl $testEWSUrl -AttachmentToken $testAttachmentToken -ExtraProperties $testExtraProperties -ExtraPropertiesTableName 'contact' -WhatIf
        # WhatIf should not return a result
        $result | Should -BeNullOrEmpty
    }
}
