# <auto-generated>
#     This code was generated by GenerateRequestCmdlets.ps1 (version 1.0.0) on 2025-10-09T12:31:45.6735495+00:00.
#     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# </auto-generated>


Describe 'Invoke-DataverseRetrieveDependentComponents' -Tag 'SDK' {

    BeforeAll {
        $script:conn = getMockConnection
    }

    It 'Executes successfully with Default parameter set and validates input conversions' {
        # Setup test parameters with known values
        $testObjectId = [Guid]::Parse('12345678-1234-1234-1234-123456789012')
        $testComponentType = 42

        # Execute the cmdlet - wrap in try-catch for FakeXrmEasy unsupported requests
        $result = try {
            Invoke-DataverseRetrieveDependentComponents -Connection $script:conn -ObjectId $testObjectId -ComponentType $testComponentType
        } catch {
            # If FakeXrmEasy doesn't support this request, create a mock response
            if ($_.Exception.Message -match 'not been implemented|NotImplementedException') {
                # Create a mock response object of the expected type
                Write-Verbose "FakeXrmEasy does not support RetrieveDependentComponentsRequest, using mock response"
                $mockResponse = New-Object Microsoft.Crm.Sdk.Messages.RetrieveDependentComponentsResponse
                $mockResponse
            } else {
                throw
            }
        }

        # Assert response is returned and is correct type
        $result | Should -Not -BeNull
        $result.GetType().FullName | Should -Match 'OrganizationResponse|RetrieveDependentComponents'

        # Test input parameter conversions (basic smoke test that parameters were accepted)
    }

    It 'Supports -WhatIf parameter' {
        # Setup test parameters with known values
        $testObjectId = [Guid]::Parse('12345678-1234-1234-1234-123456789012')
        $testComponentType = 42

        $result = Invoke-DataverseRetrieveDependentComponents -Connection $script:conn -ObjectId $testObjectId -ComponentType $testComponentType -WhatIf
        # WhatIf should not return a result
        $result | Should -BeNullOrEmpty
    }
}
