# <auto-generated>
#     This code was generated by GenerateRequestCmdlets.ps1 (version 1.0.0) on 2025-10-08T20:30:44.8614798+00:00.
#     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# </auto-generated>

. $PSScriptRoot/../Common.ps1

Describe 'Invoke-DataverseRemoveItemCampaignActivity' {

    BeforeAll {
        $script:conn = getMockConnection
    }

    It 'Can invoke the cmdlet with a mock connection' {
        {
            # Create test parameters
            $CampaignActivityId = [Guid]::NewGuid()
            $ItemId = [Guid]::NewGuid()

            $result = Invoke-DataverseRemoveItemCampaignActivity -Connection $script:conn -CampaignActivityId $CampaignActivityId -ItemId $ItemId
            $result | Should -Not -BeNull
        } | Should -Not -Throw
    }

    It 'Supports -WhatIf parameter' {
        {
            # Basic WhatIf test - may need parameter adjustment
            $result = Invoke-DataverseRemoveItemCampaignActivity -Connection $script:conn -WhatIf
        } | Should -Not -Throw
    }
}
