# <auto-generated>
#     This code was generated by GenerateRequestCmdlets.ps1 (version 1.0.0) on 2025-10-08T20:30:51.0928004+00:00.
#     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# </auto-generated>

. $PSScriptRoot/../Common.ps1

Describe 'Invoke-DataverseConvertQuoteToSalesOrder' {

    BeforeAll {
        $script:conn = getMockConnection
    }

    It 'Can invoke the cmdlet with a mock connection' {
        {
            # Create test parameters
            $QuoteId = [Guid]::NewGuid()
            $ColumnSet = New-Object Microsoft.Xrm.Sdk.Query.ColumnSet($true)
            $QuoteCloseSubject = "TestQuoteCloseSubject"
            $QuoteCloseDescription = "TestQuoteCloseDescription"
            $ProcessInstanceId = @{ Id = [Guid]::NewGuid(); LogicalName = 'contact' }

            $result = Invoke-DataverseConvertQuoteToSalesOrder -Connection $script:conn -QuoteId $QuoteId -ColumnSet $ColumnSet -QuoteCloseSubject $QuoteCloseSubject -QuoteCloseDescription $QuoteCloseDescription -ProcessInstanceId $ProcessInstanceId
            $result | Should -Not -BeNull
        } | Should -Not -Throw
    }

    It 'Supports -WhatIf parameter' {
        {
            # Basic WhatIf test - may need parameter adjustment
            $result = Invoke-DataverseConvertQuoteToSalesOrder -Connection $script:conn -WhatIf
        } | Should -Not -Throw
    }
}
