# <auto-generated>
#     This code was generated by GenerateRequestCmdlets.ps1 (version 1.0.0) on 2025-10-08T20:29:18.9161987+00:00.
#     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# </auto-generated>

. $PSScriptRoot/../Common.ps1

Describe 'Invoke-DataverseAddToQueue' {

    BeforeAll {
        $script:conn = getMockConnection
    }

    It 'Can invoke the cmdlet with a mock connection' {
        {
            $testEntity = @{ firstname = 'Test'; lastname = 'User' }
            # Create test entity
            # Create test parameters
            $Target = @{ Id = [Guid]::NewGuid(); LogicalName = 'contact' }
            $SourceQueueId = [Guid]::NewGuid()
            $DestinationQueueId = [Guid]::NewGuid()
            $QueueItemProperties = $testEntity

            $result = Invoke-DataverseAddToQueue -Connection $script:conn -Target $Target -SourceQueueId $SourceQueueId -DestinationQueueId $DestinationQueueId -QueueItemProperties $QueueItemProperties
            $result | Should -Not -BeNull
        } | Should -Not -Throw
    }

    It 'Supports -WhatIf parameter' {
        {
            # Basic WhatIf test - may need parameter adjustment
            $result = Invoke-DataverseAddToQueue -Connection $script:conn -WhatIf
        } | Should -Not -Throw
    }
}
