# <auto-generated>
#     This code was generated by GenerateRequestCmdlets.ps1 (version 1.0.0) on 2025-10-08T20:29:10.9636361+00:00.
#     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# </auto-generated>

. $PSScriptRoot/../Common.ps1

Describe 'Invoke-DataverseSearchByBodyKbArticle' {

    BeforeAll {
        $script:conn = getMockConnection
    }

    It 'Can invoke the cmdlet with a mock connection' {
        {
            # Create test parameters
            $SearchText = "TestSearchText"
            $SubjectId = [Guid]::NewGuid()
            $UseInflection = $true
            $QueryExpression = New-Object Microsoft.Xrm.Sdk.Query.QueryExpression('contact')

            $result = Invoke-DataverseSearchByBodyKbArticle -Connection $script:conn -SearchText $SearchText -SubjectId $SubjectId -UseInflection $UseInflection -QueryExpression $QueryExpression
            $result | Should -Not -BeNull
        } | Should -Not -Throw
    }

    It 'Supports -WhatIf parameter' {
        {
            # Basic WhatIf test - may need parameter adjustment
            $result = Invoke-DataverseSearchByBodyKbArticle -Connection $script:conn -WhatIf
        } | Should -Not -Throw
    }
}
