# <auto-generated>
#     This code was generated by GenerateRequestCmdlets.ps1 (version 1.0.0) on 2025-10-08T21:03:21.5277006+00:00.
#     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# </auto-generated>

. $PSScriptRoot/../Common.ps1

Describe 'Invoke-DataverseUpdateOptionValue' -Tag 'SDK' {

    BeforeAll {
        $script:conn = getMockConnection
    }

    It 'Executes successfully with Default parameter set' {
        # Setup test parameters with known values
        $testOptionSetName = "TestOptionSetNameValue"
        $testAttributeLogicalName = "TestAttributeLogicalNameValue"
        $testEntityLogicalName = "TestEntityLogicalNameValue"
        $testValue = 42
        $testMergeLabels = $true
        $testSolutionUniqueName = "TestSolutionUniqueNameValue"

        $result = Invoke-DataverseUpdateOptionValue -Connection $script:conn -OptionSetName $testOptionSetName -AttributeLogicalName $testAttributeLogicalName -EntityLogicalName $testEntityLogicalName -Value $testValue -MergeLabels $testMergeLabels -SolutionUniqueName $testSolutionUniqueName

        # Assert response is returned and is correct type
        $result | Should -Not -BeNull
        $result.GetType().FullName | Should -Match 'OrganizationResponse|UpdateOptionValue'
    }

}
