# <auto-generated>
#     This code was generated by GenerateRequestCmdlets.ps1 (version 1.0.0) on 2025-10-08T20:30:19.0442509+00:00.
#     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# </auto-generated>

. $PSScriptRoot/../Common.ps1

Describe 'Invoke-DataverseRetrieveUserPrivilegeByPrivilegeName' {

    BeforeAll {
        $script:conn = getMockConnection
    }

    It 'Can invoke the cmdlet with a mock connection' {
        {
            # Create test parameters
            $UserId = [Guid]::NewGuid()
            $PrivilegeName = "TestPrivilegeName"

            $result = Invoke-DataverseRetrieveUserPrivilegeByPrivilegeName -Connection $script:conn -UserId $UserId -PrivilegeName $PrivilegeName
            $result | Should -Not -BeNull
        } | Should -Not -Throw
    }

    It 'Supports -WhatIf parameter' {
        {
            # Basic WhatIf test - may need parameter adjustment
            $result = Invoke-DataverseRetrieveUserPrivilegeByPrivilegeName -Connection $script:conn -WhatIf
        } | Should -Not -Throw
    }
}
