# <auto-generated>
#     This code was generated by GenerateRequestCmdlets.ps1 (version 1.0.0) on 2025-10-08T20:29:15.2301586+00:00.
#     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# </auto-generated>

. $PSScriptRoot/../Common.ps1

Describe 'Invoke-DataverseRetrieveRecordWall' {

    BeforeAll {
        $script:conn = getMockConnection
    }

    It 'Can invoke the cmdlet with a mock connection' {
        {
            # Create test parameters
            $Entity = @{ Id = [Guid]::NewGuid(); LogicalName = 'contact' }
            $PageNumber = 1
            $PageSize = 1
            $CommentsPerPost = 1
            $SortDirection = $true
            $Keyword = "TestKeyword"

            $result = Invoke-DataverseRetrieveRecordWall -Connection $script:conn -Entity $Entity -PageNumber $PageNumber -PageSize $PageSize -CommentsPerPost $CommentsPerPost -SortDirection $SortDirection -Keyword $Keyword
            $result | Should -Not -BeNull
        } | Should -Not -Throw
    }

    It 'Supports -WhatIf parameter' {
        {
            # Basic WhatIf test - may need parameter adjustment
            $result = Invoke-DataverseRetrieveRecordWall -Connection $script:conn -WhatIf
        } | Should -Not -Throw
    }
}
