# <auto-generated>
#     This code was generated by GenerateRequestCmdlets.ps1 (version 1.0.0) on 2025-10-08T21:02:55.7693089+00:00.
#     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# </auto-generated>

. $PSScriptRoot/../Common.ps1

Describe 'Invoke-DataverseRenewContract' -Tag 'SDK' {

    BeforeAll {
        $script:conn = getMockConnection
    }

    It 'Executes successfully with Default parameter set' {
        # Setup test parameters with known values
        $testContractId = [Guid]::Parse('12345678-1234-1234-1234-123456789012')
        $testStatus = 42
        $testIncludeCanceledLines = $true

        $result = Invoke-DataverseRenewContract -Connection $script:conn -ContractId $testContractId -Status $testStatus -IncludeCanceledLines $testIncludeCanceledLines

        # Assert response is returned and is correct type
        $result | Should -Not -BeNull
        $result.GetType().FullName | Should -Match 'OrganizationResponse|RenewContract'
    }

}
