# <auto-generated>
#     This code was generated by GenerateRequestCmdlets.ps1 (version 1.0.0) on 2025-10-08T20:30:39.3946152+00:00.
#     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# </auto-generated>

. $PSScriptRoot/../Common.ps1

Describe 'Invoke-DataverseCopyCampaign' {

    BeforeAll {
        $script:conn = getMockConnection
    }

    It 'Can invoke the cmdlet with a mock connection' {
        {
            # Create test parameters
            $BaseCampaign = [Guid]::NewGuid()
            $SaveAsTemplate = $true

            $result = Invoke-DataverseCopyCampaign -Connection $script:conn -BaseCampaign $BaseCampaign -SaveAsTemplate $SaveAsTemplate
            $result | Should -Not -BeNull
        } | Should -Not -Throw
    }

    It 'Supports -WhatIf parameter' {
        {
            # Basic WhatIf test - may need parameter adjustment
            $result = Invoke-DataverseCopyCampaign -Connection $script:conn -WhatIf
        } | Should -Not -Throw
    }
}
