# <auto-generated>
#     This code was generated by GenerateRequestCmdlets.ps1 (version 1.0.0) on 2025-10-08T21:02:24.6342008+00:00.
#     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# </auto-generated>

. $PSScriptRoot/../Common.ps1

Describe 'Invoke-DataverseSetParentBusinessUnit' -Tag 'SDK' {

    BeforeAll {
        $script:conn = getMockConnection
    }

    It 'Executes successfully with Default parameter set' {
        # Setup test parameters with known values
        $testBusinessUnitId = [Guid]::Parse('12345678-1234-1234-1234-123456789012')
        $testParentId = [Guid]::Parse('12345678-1234-1234-1234-123456789012')

        $result = Invoke-DataverseSetParentBusinessUnit -Connection $script:conn -BusinessUnitId $testBusinessUnitId -ParentId $testParentId

        # Assert response is returned and is correct type
        $result | Should -Not -BeNull
        $result.GetType().FullName | Should -Match 'OrganizationResponse|SetParentBusinessUnit'
    }

}
