# <auto-generated>
#     This code was generated by GenerateRequestCmdlets.ps1 (version 1.0.0) on 2025-10-08T21:01:44.1472574+00:00.
#     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# </auto-generated>

. $PSScriptRoot/../Common.ps1

Describe 'Invoke-DataverseSendEmailFromTemplate' -Tag 'SDK' {

    BeforeAll {
        $script:conn = getMockConnection
    }

    It 'Executes successfully with Default parameter set' {
        # Setup test parameters with known values
        $testTemplateId = [Guid]::Parse('12345678-1234-1234-1234-123456789012')
        $testRegardingType = "TestRegardingTypeValue"
        $testRegardingId = [Guid]::Parse('12345678-1234-1234-1234-123456789012')
        $testTarget = @{ firstname = 'TestFirst'; lastname = 'TestLast'; contactid = [Guid]::NewGuid() }

        $result = Invoke-DataverseSendEmailFromTemplate -Connection $script:conn -TemplateId $testTemplateId -RegardingType $testRegardingType -RegardingId $testRegardingId -Target $testTarget -TargetTableName 'contact'

        # Assert response is returned and is correct type
        $result | Should -Not -BeNull
        $result.GetType().FullName | Should -Match 'OrganizationResponse|SendEmailFromTemplate'
    }

}
