# <auto-generated>
#     This code was generated by GenerateRequestCmdlets.ps1 (version 1.0.0) on 2025-10-08T20:30:16.3647383+00:00.
#     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# </auto-generated>

. $PSScriptRoot/../Common.ps1

Describe 'Invoke-DataverseReassignObjectsOwner' {

    BeforeAll {
        $script:conn = getMockConnection
    }

    It 'Can invoke the cmdlet with a mock connection' {
        {
            # Create test parameters
            $FromPrincipal = @{ Id = [Guid]::NewGuid(); LogicalName = 'contact' }
            $ToPrincipal = @{ Id = [Guid]::NewGuid(); LogicalName = 'contact' }

            $result = Invoke-DataverseReassignObjectsOwner -Connection $script:conn -FromPrincipal $FromPrincipal -ToPrincipal $ToPrincipal
            $result | Should -Not -BeNull
        } | Should -Not -Throw
    }

    It 'Supports -WhatIf parameter' {
        {
            # Basic WhatIf test - may need parameter adjustment
            $result = Invoke-DataverseReassignObjectsOwner -Connection $script:conn -WhatIf
        } | Should -Not -Throw
    }
}
