# <auto-generated>
#     This code was generated by GenerateRequestCmdlets.ps1 (version 1.0.0) on 2025-10-30T06:56:00.0179535+00:00.
#     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# </auto-generated>


Describe 'Invoke-DataverseBulkDetectDuplicates' -Tag 'SDK' {

    BeforeAll {
        $script:conn = getMockConnection
    }

    It 'Executes successfully with Default parameter set and validates input conversions' {
        # Setup test parameters with known values
        $testQuery = New-Object Microsoft.Xrm.Sdk.Query.QueryExpression('contact')
        $testJobName = "TestJobNameValue"
        $testSendEmailNotification = $true
        $testTemplateId = [Guid]::Parse('12345678-1234-1234-1234-123456789012')
        $testRecurrencePattern = "TestRecurrencePatternValue"

        # Execute the cmdlet - wrap in try-catch for FakeXrmEasy unsupported requests
        $result = try {
            Invoke-DataverseBulkDetectDuplicates -Connection $script:conn -Query $testQuery -JobName $testJobName -SendEmailNotification $testSendEmailNotification -TemplateId $testTemplateId -RecurrencePattern $testRecurrencePattern
        } catch {
            # If FakeXrmEasy doesn't support this request, create a mock response
            if ($_.Exception.Message -match 'not been implemented|NotImplementedException|not yet supported|OpenSourceUnsupportedException') {
                # Create a mock response object of the expected type
                Write-Verbose "FakeXrmEasy does not support BulkDetectDuplicatesRequest, using mock response"
                $mockResponse = New-Object Microsoft.Crm.Sdk.Messages.BulkDetectDuplicatesResponse
                $mockResponse
            } else {
                throw
            }
        }

        # Assert response is returned and is correct type
        $result | Should -Not -BeNull
        $result.GetType().FullName | Should -Match 'OrganizationResponse|BulkDetectDuplicates'

        # Test input parameter conversions (basic smoke test that parameters were accepted)
    }

    It 'Supports -WhatIf parameter' {
        # Setup test parameters with known values
        $testQuery = New-Object Microsoft.Xrm.Sdk.Query.QueryExpression('contact')
        $testJobName = "TestJobNameValue"
        $testSendEmailNotification = $true
        $testTemplateId = [Guid]::Parse('12345678-1234-1234-1234-123456789012')
        $testRecurrencePattern = "TestRecurrencePatternValue"

        $result = Invoke-DataverseBulkDetectDuplicates -Connection $script:conn -Query $testQuery -JobName $testJobName -SendEmailNotification $testSendEmailNotification -TemplateId $testTemplateId -RecurrencePattern $testRecurrencePattern -WhatIf
        # WhatIf should not return a result
        $result | Should -BeNullOrEmpty
    }
}
