# <auto-generated>
#     This code was generated by GenerateRequestCmdlets.ps1 (version 1.0.0) on 2025-10-08T20:29:34.2063309+00:00.
#     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# </auto-generated>

. $PSScriptRoot/../Common.ps1

Describe 'Invoke-DataverseSetFeatureStatus' {

    BeforeAll {
        $script:conn = getMockConnection
    }

    It 'Can invoke the cmdlet with a mock connection' {
        {
            # Create test parameters
            $FeatureType = 1
            $Status = $true
            $ConfigData = "TestConfigData"
            $IsSolutionUninstall = $true

            $result = Invoke-DataverseSetFeatureStatus -Connection $script:conn -FeatureType $FeatureType -Status $Status -ConfigData $ConfigData -IsSolutionUninstall $IsSolutionUninstall
            $result | Should -Not -BeNull
        } | Should -Not -Throw
    }

    It 'Supports -WhatIf parameter' {
        {
            # Basic WhatIf test - may need parameter adjustment
            $result = Invoke-DataverseSetFeatureStatus -Connection $script:conn -WhatIf
        } | Should -Not -Throw
    }
}
