# <auto-generated>
#     This code was generated by GenerateRequestCmdlets.ps1 (version 1.0.0) on 2025-10-30T08:36:00.8594750+00:00.
#     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# </auto-generated>

Describe 'Invoke-DataverseRetrieveTimestamp' -Tag 'SDK' {

    BeforeAll {
        $script:conn = getMockConnection
    }

    It 'Executes successfully with no parameters and returns correct response type' {
        # Execute the cmdlet - wrap in try-catch for FakeXrmEasy unsupported requests
        $result = try {
            Invoke-DataverseRetrieveTimestamp -Connection $script:conn
        } catch {
            # If FakeXrmEasy doesn't support this request, create a mock response
            if ($_.Exception.Message -match 'not been implemented|NotImplementedException|not yet supported|OpenSourceUnsupportedException') {
                # Create a mock response object of the expected type
                Write-Verbose "FakeXrmEasy does not support RetrieveTimestampRequest, using mock response"
                $mockResponse = New-Object Microsoft.Xrm.Sdk.Messages.RetrieveTimestampResponse
                $mockResponse
            } else {
                throw
            }
        }

        # Assert response is returned and is correct type
        $result | Should -Not -BeNull
        $result.GetType().FullName | Should -Match 'OrganizationResponse|RetrieveTimestamp'
    }

    It 'Supports -WhatIf parameter' {
        $result = Invoke-DataverseRetrieveTimestamp -Connection $script:conn -WhatIf
        # WhatIf should not return a result
        $result | Should -BeNullOrEmpty
    }
}
