# <auto-generated>
#     This code was generated by GenerateRequestCmdlets.ps1 (version 1.0.0) on 2025-10-30T06:51:47.9858613+00:00.
#     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# </auto-generated>

. $PSScriptRoot/../Common.ps1

Describe 'Invoke-DataverseWhoAmI' -Tag 'SDK' {

    BeforeAll {
        $script:conn = getMockConnection
    }

    It 'Executes successfully with no parameters and returns correct response type' {
        $result = Invoke-DataverseWhoAmI -Connection $script:conn

        # Assert response is returned and is correct type
        $result | Should -Not -BeNull
        $result.GetType().FullName | Should -Match 'OrganizationResponse|WhoAmI'
    }

    It 'Supports -WhatIf parameter' {
        $result = Invoke-DataverseWhoAmI -Connection $script:conn -WhatIf
        # WhatIf should not return a result
        $result | Should -BeNullOrEmpty
    }
}
