# <auto-generated>
#     This code was generated by GenerateRequestCmdlets.ps1 (version 1.0.0) on 2025-10-08T20:29:03.5866904+00:00.
#     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# </auto-generated>

. $PSScriptRoot/../Common.ps1

Describe 'Invoke-DataverseCheckPromoteEmail' {

    BeforeAll {
        $script:conn = getMockConnection
    }

    It 'Can invoke the cmdlet with a mock connection' {
        {
            # Create test parameters
            $MessageId = "TestMessageId"
            $Subject = "TestSubject"
            $DirectionCode = 1

            $result = Invoke-DataverseCheckPromoteEmail -Connection $script:conn -MessageId $MessageId -Subject $Subject -DirectionCode $DirectionCode
            $result | Should -Not -BeNull
        } | Should -Not -Throw
    }

    It 'Supports -WhatIf parameter' {
        {
            # Basic WhatIf test - may need parameter adjustment
            $result = Invoke-DataverseCheckPromoteEmail -Connection $script:conn -WhatIf
        } | Should -Not -Throw
    }
}
