# <auto-generated>
#     This code was generated by GenerateRequestCmdlets.ps1 (version 1.0.0) on 2025-10-08T21:03:00.3856150+00:00.
#     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# </auto-generated>

. $PSScriptRoot/../Common.ps1

Describe 'Invoke-DataverseRetrieveFeatureControlSetting' -Tag 'SDK' {

    BeforeAll {
        $script:conn = getMockConnection
    }

    It 'Executes successfully with Default parameter set' {
        # Setup test parameters with known values
        $testNamespaceValue = "TestNamespaceValueValue"
        $testFeatureControlName = "TestFeatureControlNameValue"

        $result = Invoke-DataverseRetrieveFeatureControlSetting -Connection $script:conn -NamespaceValue $testNamespaceValue -FeatureControlName $testFeatureControlName

        # Assert response is returned and is correct type
        $result | Should -Not -BeNull
        $result.GetType().FullName | Should -Match 'OrganizationResponse|RetrieveFeatureControlSetting'
    }

}
