# <auto-generated>
#     This code was generated by GenerateRequestCmdlets.ps1 (version 1.0.0) on 2025-10-09T12:07:30.0954511+00:00.
#     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# </auto-generated>

. $PSScriptRoot/../Common.ps1

Describe 'Invoke-DataverseIsValidStateTransition' -Tag 'SDK' {

    BeforeAll {
        $script:conn = getMockConnection
    }

    It 'Executes successfully with Default parameter set and validates input conversions' {
        # Setup test parameters with known values
        $testEntityId = [Guid]::Parse('87654321-4321-4321-4321-210987654321')
        $testEntity = @{ Id = $testEntityId; LogicalName = 'contact' }
        $testNewState = "TestNewStateValue"
        $testNewStatus = 42

        # Execute the cmdlet - wrap in try-catch for FakeXrmEasy unsupported requests
        $result = try {
            Invoke-DataverseIsValidStateTransition -Connection $script:conn -Entity $testEntity -NewState $testNewState -NewStatus $testNewStatus
        } catch {
            # If FakeXrmEasy doesn't support this request, create a mock response
            if ($_.Exception.Message -match 'not been implemented|NotImplementedException') {
                # Create a mock response object of the expected type
                Write-Verbose "FakeXrmEasy does not support IsValidStateTransitionRequest, using mock response"
                $mockResponse = New-Object Microsoft.Crm.Sdk.Messages.IsValidStateTransitionResponse
                $mockResponse
            } else {
                throw
            }
        }

        # Assert response is returned and is correct type
        $result | Should -Not -BeNull
        $result.GetType().FullName | Should -Match 'OrganizationResponse|IsValidStateTransition'

        # Test input parameter conversions (basic smoke test that parameters were accepted)
        # Validated that PSObject/Hashtable $testEntity was accepted and converted to EntityReference
    }

    It 'Supports -WhatIf parameter' {
        # Setup test parameters with known values
        $testEntityId = [Guid]::Parse('87654321-4321-4321-4321-210987654321')
        $testEntity = @{ Id = $testEntityId; LogicalName = 'contact' }
        $testNewState = "TestNewStateValue"
        $testNewStatus = 42

        $result = Invoke-DataverseIsValidStateTransition -Connection $script:conn -Entity $testEntity -NewState $testNewState -NewStatus $testNewStatus -WhatIf
        # WhatIf should not return a result
        $result | Should -BeNullOrEmpty
    }
}
