# <auto-generated>
#     This code was generated by GenerateRequestCmdlets.ps1 (version 1.0.0) on 2025-10-08T20:30:51.9984182+00:00.
#     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# </auto-generated>

. $PSScriptRoot/../Common.ps1

Describe 'Invoke-DataverseFulfillSalesOrder' {

    BeforeAll {
        $script:conn = getMockConnection
    }

    It 'Can invoke the cmdlet with a mock connection' {
        {
            $testEntity = @{ firstname = 'Test'; lastname = 'User' }
            # Create test entity
            # Create test parameters
            $OrderClose = $testEntity

            $result = Invoke-DataverseFulfillSalesOrder -Connection $script:conn -OrderClose $OrderClose
            $result | Should -Not -BeNull
        } | Should -Not -Throw
    }

    It 'Supports -WhatIf parameter' {
        {
            # Basic WhatIf test - may need parameter adjustment
            $result = Invoke-DataverseFulfillSalesOrder -Connection $script:conn -WhatIf
        } | Should -Not -Throw
    }
}
