# <auto-generated>
#     This code was generated by GenerateRequestCmdlets.ps1 (version 1.0.0) on 2025-10-08T21:02:46.0081684+00:00.
#     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# </auto-generated>

. $PSScriptRoot/../Common.ps1

Describe 'Invoke-DataversePropagateByExpression' -Tag 'SDK' {

    BeforeAll {
        $script:conn = getMockConnection
    }

    It 'Executes successfully with Default parameter set' {
        # Setup test parameters with known values
        $testQueryExpression = New-Object Microsoft.Xrm.Sdk.Query.QueryExpression('contact')
        $testFriendlyName = "TestFriendlyNameValue"
        $testExecuteImmediately = $true
        $testActivity = @{ firstname = 'TestFirst'; lastname = 'TestLast'; contactid = [Guid]::NewGuid() }
        $testTemplateId = [Guid]::Parse('12345678-1234-1234-1234-123456789012')
        $testPostWorkflowEvent = $true
        $testOwnerId = [Guid]::Parse('87654321-4321-4321-4321-210987654321')
        $testOwner = @{ Id = $testOwnerId; LogicalName = 'contact' }
        $testSendEmail = $true
        $testQueueId = [Guid]::Parse('12345678-1234-1234-1234-123456789012')

        $result = Invoke-DataversePropagateByExpression -Connection $script:conn -QueryExpression $testQueryExpression -FriendlyName $testFriendlyName -ExecuteImmediately $testExecuteImmediately -Activity $testActivity -ActivityTableName 'contact' -TemplateId $testTemplateId -PostWorkflowEvent $testPostWorkflowEvent -Owner $testOwner -SendEmail $testSendEmail -QueueId $testQueueId

        # Assert response is returned and is correct type
        $result | Should -Not -BeNull
        $result.GetType().FullName | Should -Match 'OrganizationResponse|PropagateByExpression'
    }

}
