# <auto-generated>
#     This code was generated by GenerateRequestCmdlets.ps1 (version 1.0.0) on 2025-10-08T21:01:42.1136014+00:00.
#     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# </auto-generated>

. $PSScriptRoot/../Common.ps1

Describe 'Invoke-DataverseDeliverPromoteEmail' -Tag 'SDK' {

    BeforeAll {
        $script:conn = getMockConnection
    }

    It 'Executes successfully with Default parameter set' {
        # Setup test parameters with known values
        $testEmailId = [Guid]::Parse('12345678-1234-1234-1234-123456789012')
        $testMessageId = "TestMessageIdValue"
        $testSubject = "TestSubjectValue"
        $testFrom = "TestFromValue"
        $testTo = "TestToValue"
        $testCc = "TestCcValue"
        $testBcc = "TestBccValue"
        $testSubmittedBy = "TestSubmittedByValue"
        $testImportance = "TestImportanceValue"
        $testBody = "TestBodyValue"
        $testExtraProperties = @{ firstname = 'TestFirst'; lastname = 'TestLast'; contactid = [Guid]::NewGuid() }

        $result = Invoke-DataverseDeliverPromoteEmail -Connection $script:conn -EmailId $testEmailId -MessageId $testMessageId -Subject $testSubject -From $testFrom -To $testTo -Cc $testCc -Bcc $testBcc -SubmittedBy $testSubmittedBy -Importance $testImportance -Body $testBody -ExtraProperties $testExtraProperties -ExtraPropertiesTableName 'contact'

        # Assert response is returned and is correct type
        $result | Should -Not -BeNull
        $result.GetType().FullName | Should -Match 'OrganizationResponse|DeliverPromoteEmail'
    }

}
