# <auto-generated>
#     This code was generated by GenerateRequestCmdlets.ps1 (version 1.0.0) on 2025-10-08T21:03:07.5154623+00:00.
#     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# </auto-generated>

. $PSScriptRoot/../Common.ps1

Describe 'Invoke-DataverseCreateEntityKey' -Tag 'SDK' {

    BeforeAll {
        $script:conn = getMockConnection
    }

    It 'Executes successfully with Default parameter set' {
        # Setup test parameters with known values
        $testEntityName = "TestEntityNameValue"
        $testSolutionUniqueName = "TestSolutionUniqueNameValue"

        $result = Invoke-DataverseCreateEntityKey -Connection $script:conn -EntityName $testEntityName -SolutionUniqueName $testSolutionUniqueName

        # Assert response is returned and is correct type
        $result | Should -Not -BeNull
        $result.GetType().FullName | Should -Match 'OrganizationResponse|CreateEntityKey'
    }

}
