# <auto-generated>
#     This code was generated by GenerateRequestCmdlets.ps1 (version 1.0.0) on 2025-10-08T20:29:58.7627169+00:00.
#     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# </auto-generated>

. $PSScriptRoot/../Common.ps1

Describe 'Invoke-DataverseBulkDetectDuplicates' {

    BeforeAll {
        $script:conn = getMockConnection
    }

    It 'Can invoke the cmdlet with a mock connection' {
        {
            # Create test parameters
            $Query = New-Object Microsoft.Xrm.Sdk.Query.QueryExpression('contact')
            $JobName = "TestJobName"
            $SendEmailNotification = $true
            $TemplateId = [Guid]::NewGuid()
            $RecurrencePattern = "TestRecurrencePattern"

            $result = Invoke-DataverseBulkDetectDuplicates -Connection $script:conn -Query $Query -JobName $JobName -SendEmailNotification $SendEmailNotification -TemplateId $TemplateId -ToRecipients $ToRecipients -CCRecipients $CCRecipients -RecurrencePattern $RecurrencePattern
            $result | Should -Not -BeNull
        } | Should -Not -Throw
    }

    It 'Supports -WhatIf parameter' {
        {
            # Basic WhatIf test - may need parameter adjustment
            $result = Invoke-DataverseBulkDetectDuplicates -Connection $script:conn -WhatIf
        } | Should -Not -Throw
    }
}
