# <auto-generated>
#     This code was generated by GenerateRequestCmdlets.ps1 (version 1.0.0) on 2025-10-30T08:17:08.8253966+00:00.
#     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# </auto-generated>

Describe 'Invoke-DataverseCreateManyToMany' -Tag 'SDK' {

    BeforeAll {
        $script:conn = getMockConnection
    }

    It 'Executes successfully with Default parameter set and validates input conversions' {
        # Setup test parameters with known values
        $testIntersectEntitySchemaName = "TestIntersectEntitySchemaNameValue"
        $testSolutionUniqueName = "TestSolutionUniqueNameValue"

        # Execute the cmdlet - wrap in try-catch for FakeXrmEasy unsupported requests
        $result = try {
            Invoke-DataverseCreateManyToMany -Connection $script:conn -IntersectEntitySchemaName $testIntersectEntitySchemaName -SolutionUniqueName $testSolutionUniqueName
        } catch {
            # If FakeXrmEasy doesn't support this request, create a mock response
            if ($_.Exception.Message -match 'not been implemented|NotImplementedException|not yet supported|OpenSourceUnsupportedException') {
                # Create a mock response object of the expected type
                Write-Verbose "FakeXrmEasy does not support CreateManyToManyRequest, using mock response"
                $mockResponse = New-Object Microsoft.Xrm.Sdk.Messages.CreateManyToManyResponse
                $mockResponse
            } else {
                throw
            }
        }

        # Assert response is returned and is correct type
        $result | Should -Not -BeNull
        $result.GetType().FullName | Should -Match 'OrganizationResponse|CreateManyToMany'

        # Test input parameter conversions (basic smoke test that parameters were accepted)
    }

    It 'Supports -WhatIf parameter' {
        # Setup test parameters with known values
        $testIntersectEntitySchemaName = "TestIntersectEntitySchemaNameValue"
        $testSolutionUniqueName = "TestSolutionUniqueNameValue"

        $result = Invoke-DataverseCreateManyToMany -Connection $script:conn -IntersectEntitySchemaName $testIntersectEntitySchemaName -SolutionUniqueName $testSolutionUniqueName -WhatIf
        # WhatIf should not return a result
        $result | Should -BeNullOrEmpty
    }
}
