# <auto-generated>
#     This code was generated by GenerateRequestCmdlets.ps1 (version 1.0.0) on 2025-10-08T21:02:23.1521978+00:00.
#     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# </auto-generated>

. $PSScriptRoot/../Common.ps1

Describe 'Invoke-DataverseRetrieveMissingComponents' -Tag 'SDK' {

    BeforeAll {
        $script:conn = getMockConnection
    }

    It 'Executes successfully with Default parameter set' {
        # Setup test parameters with known values
        $testCustomizationFile = [System.Text.Encoding]::UTF8.GetBytes('TestDataCustomizationFile')

        $result = Invoke-DataverseRetrieveMissingComponents -Connection $script:conn -CustomizationFile $testCustomizationFile

        # Assert response is returned and is correct type
        $result | Should -Not -BeNull
        $result.GetType().FullName | Should -Match 'OrganizationResponse|RetrieveMissingComponents'
    }

    It 'Executes successfully with FromFile parameter set' {
        # Create a temporary test file
        $testFilePath = [System.IO.Path]::GetTempFileName()
        $testData = 'TestFileDataForByteArray'
        [System.IO.File]::WriteAllText($testFilePath, $testData)

        try {
            # Setup test parameters with known values

            $result = Invoke-DataverseRetrieveMissingComponents -Connection $script:conn -InFile $testFilePath

            # Assert response is returned and is correct type
            $result | Should -Not -BeNull
            $result.GetType().FullName | Should -Match 'OrganizationResponse|RetrieveMissingComponents'
        } finally {
            if (Test-Path $testFilePath) {
                Remove-Item $testFilePath -Force
            }
        }
    }

}
