# <auto-generated>
#     This code was generated by GenerateRequestCmdlets.ps1 (version 1.0.0) on 2025-10-08T21:01:50.1087755+00:00.
#     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# </auto-generated>

. $PSScriptRoot/../Common.ps1

Describe 'Invoke-DataverseAddToQueue' -Tag 'SDK' {

    BeforeAll {
        $script:conn = getMockConnection
    }

    It 'Executes successfully with Default parameter set' {
        # Setup test parameters with known values
        $testTargetId = [Guid]::Parse('87654321-4321-4321-4321-210987654321')
        $testTarget = @{ Id = $testTargetId; LogicalName = 'contact' }
        $testSourceQueueId = [Guid]::Parse('12345678-1234-1234-1234-123456789012')
        $testDestinationQueueId = [Guid]::Parse('12345678-1234-1234-1234-123456789012')
        $testQueueItemProperties = @{ firstname = 'TestFirst'; lastname = 'TestLast'; contactid = [Guid]::NewGuid() }

        $result = Invoke-DataverseAddToQueue -Connection $script:conn -Target $testTarget -SourceQueueId $testSourceQueueId -DestinationQueueId $testDestinationQueueId -QueueItemProperties $testQueueItemProperties -QueueItemPropertiesTableName 'contact'

        # Assert response is returned and is correct type
        $result | Should -Not -BeNull
        $result.GetType().FullName | Should -Match 'OrganizationResponse|AddToQueue'
    }

}
