# <auto-generated>
#     This code was generated by GenerateRequestCmdlets.ps1 (version 1.0.0) on 2025-10-08T21:02:54.6390258+00:00.
#     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# </auto-generated>

. $PSScriptRoot/../Common.ps1

Describe 'Invoke-DataverseWinQuote' -Tag 'SDK' {

    BeforeAll {
        $script:conn = getMockConnection
    }

    It 'Executes successfully with Default parameter set' {
        # Setup test parameters with known values
        $testQuoteClose = @{ firstname = 'TestFirst'; lastname = 'TestLast'; contactid = [Guid]::NewGuid() }

        $result = Invoke-DataverseWinQuote -Connection $script:conn -QuoteClose $testQuoteClose -QuoteCloseTableName 'contact'

        # Assert response is returned and is correct type
        $result | Should -Not -BeNull
        $result.GetType().FullName | Should -Match 'OrganizationResponse|WinQuote'
    }

}
