# <auto-generated>
#     This code was generated by GenerateRequestCmdlets.ps1 (version 1.0.0) on 2025-10-08T21:02:13.8921244+00:00.
#     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# </auto-generated>

. $PSScriptRoot/../Common.ps1

Describe 'Invoke-DataverseQueryExpressionToFetchXml' -Tag 'SDK' {

    BeforeAll {
        $script:conn = getMockConnection
    }

    It 'Executes successfully with Default parameter set' {
        # Setup test parameters with known values
        $testQuery = New-Object Microsoft.Xrm.Sdk.Query.QueryExpression('contact')

        $result = Invoke-DataverseQueryExpressionToFetchXml -Connection $script:conn -Query $testQuery

        # Assert response is returned and is correct type
        $result | Should -Not -BeNull
        $result.GetType().FullName | Should -Match 'OrganizationResponse|QueryExpressionToFetchXml'
    }

}
