# <auto-generated>
#     This code was generated by GenerateRequestCmdlets.ps1 (version 1.0.0) on 2025-10-30T07:48:30.0588581+00:00.
#     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# </auto-generated>

Describe 'Invoke-DataverseGetAutoNumberSeed' -Tag 'SDK' {

    BeforeAll {
        $script:conn = getMockConnection
    }

    It 'Executes successfully with Default parameter set and validates input conversions' {
        # Setup test parameters with known values
        $testEntityName = "TestEntityNameValue"
        $testAttributeName = "TestAttributeNameValue"

        # Execute the cmdlet - wrap in try-catch for FakeXrmEasy unsupported requests
        $result = try {
            Invoke-DataverseGetAutoNumberSeed -Connection $script:conn -EntityName $testEntityName -AttributeName $testAttributeName
        } catch {
            # If FakeXrmEasy doesn't support this request, create a mock response
            if ($_.Exception.Message -match 'not been implemented|NotImplementedException|not yet supported|OpenSourceUnsupportedException') {
                # Create a mock response object of the expected type
                Write-Verbose "FakeXrmEasy does not support GetAutoNumberSeedRequest, using mock response"
                $mockResponse = New-Object Microsoft.Crm.Sdk.Messages.GetAutoNumberSeedResponse
                $mockResponse
            } else {
                throw
            }
        }

        # Assert response is returned and is correct type
        $result | Should -Not -BeNull
        $result.GetType().FullName | Should -Match 'OrganizationResponse|GetAutoNumberSeed'

        # Test input parameter conversions (basic smoke test that parameters were accepted)
    }

    It 'Supports -WhatIf parameter' {
        # Setup test parameters with known values
        $testEntityName = "TestEntityNameValue"
        $testAttributeName = "TestAttributeNameValue"

        $result = Invoke-DataverseGetAutoNumberSeed -Connection $script:conn -EntityName $testEntityName -AttributeName $testAttributeName -WhatIf
        # WhatIf should not return a result
        $result | Should -BeNullOrEmpty
    }
}
