# <auto-generated>
#     This code was generated by GenerateRequestCmdlets.ps1 (version 1.0.0) on 2025-10-09T12:07:53.0612334+00:00.
#     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# </auto-generated>

. $PSScriptRoot/../Common.ps1

Describe 'Invoke-DataverseRetrieveExchangeAppointments' -Tag 'SDK' {

    BeforeAll {
        $script:conn = getMockConnection
    }

    It 'Supports -WhatIf parameter' {
        $result = Invoke-DataverseRetrieveExchangeAppointments -Connection $script:conn -WhatIf
        # WhatIf should not return a result
        $result | Should -BeNullOrEmpty
    }
}
