using System.Globalization;
using System.IO.Compression;
using System.Net.Http.Headers;
using System.Reflection;
using System.Text.Encodings.Web;
using System.Text.RegularExpressions;
using System.Text;
using System.Text.Json;
using System.Text.Json.Nodes;
using System.Xml.Linq;
using Azure.Core;
using Azure.Identity;
using YamlDotNet.Serialization;

namespace MsAppToolkit;

public static partial class YamlFirstPackaging
{    private static Dictionary<string, byte[]> ReadEntriesFromMsApp(string msappPath)
    {
        using var stream = File.OpenRead(msappPath);
        return ReadEntriesFromMsAppStream(stream);
    }

    private static Dictionary<string, byte[]> ReadEntriesFromMsAppStream(Stream source)
    {
        var entries = new Dictionary<string, byte[]>(StringComparer.OrdinalIgnoreCase);
        using var archive = new ZipArchive(source, ZipArchiveMode.Read, leaveOpen: false);
        foreach (var entry in archive.Entries)
        {
            using var stream = entry.Open();
            using var memory = new MemoryStream();
            stream.CopyTo(memory);
            entries[entry.FullName.Replace('\\', '/')] = memory.ToArray();
        }

        return entries;
    }

    private static bool ReadEmbeddedAllControlsEntries(out Dictionary<string, byte[]> entries)
    {
        entries = new Dictionary<string, byte[]>(StringComparer.OrdinalIgnoreCase);
        var assembly = typeof(YamlFirstPackaging).Assembly;
        var stream = assembly.GetManifestResourceStream("MsAppToolkit.Resources.AllControls.msapp");
        if (stream is null)
        {
            var fallback = assembly.GetManifestResourceNames()
                .FirstOrDefault(n => n.EndsWith("All controls.msapp", StringComparison.OrdinalIgnoreCase)
                                     || n.EndsWith("AllControls.msapp", StringComparison.OrdinalIgnoreCase));

            if (!string.IsNullOrWhiteSpace(fallback))
            {
                stream = assembly.GetManifestResourceStream(fallback);
            }
        }

        if (stream is null)
        {
           throw new InvalidOperationException("Could not find embedded AllControls.msapp resource. Ensure it is included in the project with the correct name.");
        }

        using (stream)
        {
            entries = ReadEntriesFromMsAppStream(stream);
            return entries.Count > 0;
        }
    }


    private static JsonObject CreateDefaultControl(string name)
    {
        return new JsonObject
        {
            ["Type"] = "ControlInfo",
            ["Name"] = name,
            ["Template"] = new JsonObject
            {
                ["Id"] = "http://microsoft.com/appmagic/label",
                ["Version"] = "2.5.1",
                ["LastModifiedTimestamp"] = "0",
                ["Name"] = "label",
                ["FirstParty"] = true,
                ["IsPremiumPcfControl"] = false,
                ["IsCustomGroupControlTemplate"] = false,
                ["CustomGroupControlTemplateName"] = "",
                ["IsComponentDefinition"] = false,
                ["OverridableProperties"] = new JsonObject(),
            },
            ["Index"] = 0,
            ["PublishOrderIndex"] = 0,
            ["VariantName"] = "",
            ["LayoutName"] = "",
            ["MetaDataIDKey"] = "",
            ["PersistMetaDataIDKey"] = false,
            ["IsFromScreenLayout"] = false,
            ["StyleName"] = "",
            ["Parent"] = "",
            ["IsDataControl"] = false,
            ["AllowAccessToGlobals"] = true,
            ["OptimizeForDevices"] = "Off",
            ["IsGroupControl"] = false,
            ["IsAutoGenerated"] = false,
            ["Rules"] = new JsonArray(),
            ["ControlPropertyState"] = new JsonArray(),
            ["IsLocked"] = false,
            ["ControlUniqueId"] = "0",
            ["Children"] = new JsonArray(),
        };
    }

    private static JsonObject CreateDefaultScreen(string name)
    {
        var screen = CreateDefaultControl(name);
        var template = (JsonObject)screen["Template"]!;
        template["Id"] = "http://microsoft.com/appmagic/screen";
        template["Name"] = "screen";
        template["Version"] = "1.0";
        screen["StyleName"] = "";
        return screen;
    }

    private static JsonObject CreateDefaultComponent(string name)
    {
        var component = CreateDefaultControl(name);
        var template = (JsonObject)component["Template"]!;
        template["Id"] = "http://microsoft.com/appmagic/Component";
        template["Name"] = Guid.NewGuid().ToString("N");
        template["Version"] = "1.0";
        template["IsComponentDefinition"] = true;
        component["AllowAccessToGlobals"] = false;
        return component;
    }

    private static JsonObject WrapTopParent(JsonObject topParent)
    {
        return new JsonObject { ["TopParent"] = topParent.DeepClone() };
    }

    private static void IndexByName(JsonObject node, Dictionary<string, JsonObject> index)
    {
        var name = node["Name"]?.GetValue<string>() ?? string.Empty;
        if (!string.IsNullOrWhiteSpace(name) && !index.ContainsKey(name))
        {
            index[name] = node;
        }

        foreach (var child in (node["Children"] as JsonArray ?? []).OfType<JsonObject>())
        {
            IndexByName(child, index);
        }
    }

    private static IEnumerable<JsonObject> Flatten(JsonObject node)
    {
        yield return node;
        foreach (var child in (node["Children"] as JsonArray ?? []).OfType<JsonObject>())
        {
            foreach (var nested in Flatten(child))
            {
                yield return nested;
            }
        }
    }

    private static Dictionary<string, JsonObject> ParseTopParentFiles(Dictionary<string, byte[]> entries, string folderPrefix)
    {
        var map = new Dictionary<string, JsonObject>(StringComparer.OrdinalIgnoreCase);
        foreach (var (path, bytes) in entries.Where(e => e.Key.StartsWith(folderPrefix, StringComparison.OrdinalIgnoreCase) && e.Key.EndsWith(".json", StringComparison.OrdinalIgnoreCase)))
        {
            var parsed = JsonNode.Parse(bytes)?.AsObject();
            if (parsed is not null)
            {
                map[path] = parsed;
            }
        }

        return map;
    }

    private static bool TryParseYamlMap(IDeserializer deserializer, string yaml, out Dictionary<object, object?> root)
    {
        root = new Dictionary<object, object?>();
        try
        {
            var parsed = deserializer.Deserialize<Dictionary<object, object?>>(yaml);
            if (parsed is null)
            {
                return false;
            }

            root = parsed;
            return true;
        }
        catch
        {
            return false;
        }
    }

    private static bool TryGetMap(Dictionary<object, object?> source, string key, out Dictionary<object, object?> map)
    {
        map = new Dictionary<object, object?>();
        if (!source.TryGetValue(key, out var val) || val is not Dictionary<object, object?> dict)
        {
            return false;
        }

        map = dict;
        return true;
    }

    private static Dictionary<string, byte[]> ReadEntries(string directory)
    {
        var entries = new Dictionary<string, byte[]>(StringComparer.OrdinalIgnoreCase);
        foreach (var path in Directory.GetFiles(directory, "*", SearchOption.AllDirectories))
        {
            var rel = Path.GetRelativePath(directory, path).Replace('\\', '/');
            entries[rel] = File.ReadAllBytes(path);
        }

        return entries;
    }

    private static void WriteMsApp(Dictionary<string, byte[]> entries, string outputMsappPath)
    {
        if (File.Exists(outputMsappPath))
        {
            File.Delete(outputMsappPath);
        }

        using var archive = ZipFile.Open(outputMsappPath, ZipArchiveMode.Create);
        foreach (var (path, data) in entries.OrderBy(e => e.Key, StringComparer.OrdinalIgnoreCase))
        {
            var entry = archive.CreateEntry(path, CompressionLevel.Optimal);
            using var stream = entry.Open();
            stream.Write(data, 0, data.Length);
        }
    }

    private static void WriteEntriesToDirectory(Dictionary<string, byte[]> entries, string outputDirectory)
    {
        foreach (var (path, data) in entries.OrderBy(e => e.Key, StringComparer.OrdinalIgnoreCase))
        {
            var fullPath = Path.Combine(outputDirectory, path.Replace('/', Path.DirectorySeparatorChar));
            var dir = Path.GetDirectoryName(fullPath);
            if (!string.IsNullOrWhiteSpace(dir))
            {
                Directory.CreateDirectory(dir);
            }

            File.WriteAllBytes(fullPath, data);
        }
    }

    private static JsonObject CreateDefaultApp(string startScreen)
    {
        var app = CreateDefaultControl("App");
        var template = (JsonObject)app["Template"]!;
        template["Id"] = "http://microsoft.com/appmagic/appinfo";
        template["Name"] = "appinfo";
        template["Version"] = "1.0";
        app["ControlUniqueId"] = "1";
        app["IsDataControl"] = true;
        app["Rules"] = new JsonArray
        {
            new JsonObject { ["Property"] = "ConfirmExit", ["Category"] = "Data", ["InvariantScript"] = "false", ["RuleProviderType"] = "Unknown" },
            new JsonObject { ["Property"] = "BackEnabled", ["Category"] = "Data", ["InvariantScript"] = "true", ["RuleProviderType"] = "Unknown" },
            new JsonObject { ["Property"] = "MinScreenHeight", ["Category"] = "Design", ["InvariantScript"] = "320", ["RuleProviderType"] = "Unknown" },
            new JsonObject { ["Property"] = "MinScreenWidth", ["Category"] = "Design", ["InvariantScript"] = "320", ["RuleProviderType"] = "Unknown" },
            new JsonObject { ["Property"] = "Theme", ["Category"] = "Design", ["InvariantScript"] = "PowerAppsTheme", ["RuleProviderType"] = "Unknown" },
            new JsonObject { ["Property"] = "OnStart", ["Category"] = "Behavior", ["InvariantScript"] = "false", ["RuleProviderType"] = "Unknown" },
            new JsonObject { ["Property"] = "SizeBreakpoints", ["Category"] = "ConstantData", ["InvariantScript"] = "[600, 900, 1200]", ["RuleProviderType"] = "Unknown" },
            new JsonObject { ["Property"] = "StartScreen", ["Category"] = "OnDemandData", ["InvariantScript"] = startScreen, ["RuleProviderType"] = "Unknown" },
        };
        app["ControlPropertyState"] = new JsonArray("ConfirmExit", "BackEnabled", "MinScreenHeight", "MinScreenWidth", "Theme", "OnStart", "SizeBreakpoints", "StartScreen");

        var host = CreateDefaultControl("Host");
        var hostTemplate = (JsonObject)host["Template"]!;
        hostTemplate["Id"] = "http://microsoft.com/appmagic/hostcontrol";
        hostTemplate["Name"] = "hostControl";
        hostTemplate["Version"] = "1.6.0";
        host["Parent"] = "App";
        host["VariantName"] = "DefaultHostControlVariant";
        host["IsDataControl"] = true;
        host["HasDynamicProperties"] = false;
        host["ControlUniqueId"] = "3";
        host["Rules"] = new JsonArray
        {
            new JsonObject { ["Property"] = "OnNew", ["Category"] = "Behavior", ["InvariantScript"] = "false", ["RuleProviderType"] = "Unknown" },
            new JsonObject { ["Property"] = "OnEdit", ["Category"] = "Behavior", ["InvariantScript"] = "false", ["RuleProviderType"] = "Unknown" },
            new JsonObject { ["Property"] = "OnView", ["Category"] = "Behavior", ["InvariantScript"] = "false", ["RuleProviderType"] = "Unknown" },
            new JsonObject { ["Property"] = "OnSave", ["Category"] = "Behavior", ["InvariantScript"] = "false", ["RuleProviderType"] = "Unknown" },
            new JsonObject { ["Property"] = "OnCancel", ["Category"] = "Behavior", ["InvariantScript"] = "false", ["RuleProviderType"] = "Unknown" },
        };
        host["ControlPropertyState"] = new JsonArray("OnNew", "OnEdit", "OnView", "OnSave", "OnCancel");

        app["Children"] = new JsonArray(host);
        return app;
    }

    private sealed class ControlIdAllocator
    {
        private readonly HashSet<int> _used = [];
        private readonly Dictionary<string, int> _nameMap = new(StringComparer.OrdinalIgnoreCase);
        private int _max;

        public ControlIdAllocator(IEnumerable<string> existing)
        {
            foreach (var id in existing)
            {
                if (int.TryParse(id, NumberStyles.Integer, CultureInfo.InvariantCulture, out var i))
                {
                    _used.Add(i);
                    if (i > _max)
                    {
                        _max = i;
                    }
                }
            }
        }

        public string GetOrCreate(string name, JsonObject? existing)
        {
            if (_nameMap.TryGetValue(name, out var mapped))
            {
                return mapped.ToString(CultureInfo.InvariantCulture);
            }

            if (existing is not null && int.TryParse(existing["ControlUniqueId"]?.GetValue<string>(), NumberStyles.Integer, CultureInfo.InvariantCulture, out var preserved))
            {
                _used.Add(preserved);
                _nameMap[name] = preserved;
                if (preserved > _max)
                {
                    _max = preserved;
                }

                return preserved.ToString(CultureInfo.InvariantCulture);
            }

            var next = _max + 1;
            while (_used.Contains(next))
            {
                next++;
            }

            _used.Add(next);
            _max = next;
            _nameMap[name] = next;
            return next.ToString(CultureInfo.InvariantCulture);
        }
    }

    private static readonly string[] HeaderLines =
    [
        "# ************************************************************************************************",
        "# Warning: YAML source code for Canvas Apps should only be used to review changes made within Power Apps Studio and for minor edits (Preview).",
        "# Use the maker portal to create and edit your Power Apps.",
        "# ",
        "# The schema file for Canvas Apps is available at https://go.microsoft.com/fwlink/?linkid=2304907",
        "# ",
        "# For more information, visit https://go.microsoft.com/fwlink/?linkid=2292623",
        "# ************************************************************************************************",
    ];
}