name: Generate TOC

on:
  push:
    paths:
      - 'docs/**/*.md'
      - '.github/workflows/toc.yml'
  pull_request:
    paths:
      - 'docs/**/*.md'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-toc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Generate TOC for all markdown files
        uses: technote-space/toc-generator@v4
        with:
          TARGET_PATHS: 'docs/**/*.md'
          TOC_TITLE: '## Table of Contents'
          FOLDING: false
          COMMIT_MESSAGE: 'docs: update table of contents [skip ci]'
          COMMIT_NAME: 'github-actions[bot]'
          COMMIT_EMAIL: 'github-actions[bot]@users.noreply.github.com'
          CREATE_PR: false
